"use client";
import LocalHostingSettings from "@/components/settings/local-hosting-settings";
import ProjectLoading from "@/components/ui/project-loading";

import { useEffect,useState } from "react";
import Link from "next/link";
import { useAuth } from "@/components/auth/auth-provider";
import { Globe,Headphones,Mail,MessageCircle,Phone,Save,Settings2,ShieldCheck } from "lucide-react";
import ProjectInput from "@/components/ui/project-input";
import { InputGroup,InputGroupTextarea } from "@/components/ui/input-group";

type Form={contact_name:string;whatsapp_number:string;whatsapp_enabled:boolean;whatsapp_button_text:string;whatsapp_message_template:string;payment_instructions:string;support_email:string;support_phone_primary:string;support_phone_secondary:string};
type Tab="payment"|"support"|"hosting";
const empty:Form={contact_name:"",whatsapp_number:"",whatsapp_enabled:true,whatsapp_button_text:"التواصل عبر واتساب لإتمام الدفع",whatsapp_message_template:"مرحبًا، أرغب بإتمام اشتراكي في Radius Lord. كود الدفع: {{payment_code}}",payment_instructions:"",support_email:"",support_phone_primary:"",support_phone_secondary:""};

export default function PlatformSettingsPage(){
 const {isMasterAdmin}=useAuth();
 const [form,setForm]=useState<Form>(empty),[activeTab,setActiveTab]=useState<Tab>("payment"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/billing/settings",{credentials:"include"}),j=await r.json();if(!r.ok)throw new Error(j.message);const m=Object.fromEntries((j.settings??[]).map((x:any)=>[x.setting_key,x.value_type==="boolean"?x.setting_value==="1":x.setting_value??""]));setForm({...empty,...m});}catch(e:any){setMessage(e.message||"تعذر تحميل الإعدادات.");}finally{setLoading(false)}})()},[]);
 const set=(k:keyof Form,v:string|boolean)=>setForm(x=>({...x,[k]:v}));
 const digits=(v:string)=>v.replace(/[^0-9]/g,"").slice(0,15);
 const setWhatsapp=(v:string)=>set("whatsapp_number",digits(v));
 const save=async()=>{setSaving(true);setMessage("");try{const number=form.whatsapp_number.replace(/[^0-9]/g,"");if(form.whatsapp_enabled&&!/^[1-9][0-9]{6,14}$/.test(number))throw new Error("رقم WhatsApp يجب أن يكون من 7 إلى 15 رقمًا بصيغة دولية، من دون + أو مسافات.");if(form.support_email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.support_email))throw new Error("أدخل بريد دعم إلكتروني صالحًا.");if([form.support_phone_primary,form.support_phone_secondary].some(v=>v&&!/^[1-9][0-9]{6,14}$/.test(v)))throw new Error("أرقام التواصل يجب أن تكون من 7 إلى 15 رقمًا بصيغة دولية.");const r=await fetch("/api/billing/settings",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,whatsapp_number:number})}),j=await r.json();if(!r.ok)throw new Error(j.message);setForm(x=>({...x,whatsapp_number:number}));setMessage("تم حفظ إعدادات التواصل والدفع بنجاح.");}catch(e:any){setMessage(e.message||"تعذر حفظ الإعدادات.");}finally{setSaving(false)}};
 return <div dir="rtl" className="mx-auto w-full max-w-6xl space-y-5">
  <div><h1 className="text-2xl font-bold text-slate-900 dark:text-white">إعدادات المنصة</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">إعدادات التواصل والدفع وربط استضافة المنصة.</p></div>
  {isMasterAdmin&&<Link href="/Dashboard/settings/homepage" className="rl-surface flex items-center gap-3 rounded-[22px] bg-white p-4 text-sm font-semibold text-[#0758e9] dark:bg-[#0d243b] dark:text-[#8fc0ff]"><Settings2 className="h-5 w-5"/>تخصيص الصفحة الرئيسية</Link>}
  <section className="rl-surface overflow-hidden rounded-[26px] border border-slate-200/80 bg-white dark:border-white/10 dark:bg-white/[.035]">
   <div className="border-b border-slate-200/70 px-4 pt-4 dark:border-white/10"><div className="flex gap-2 overflow-x-auto"><button type="button" onClick={()=>{setActiveTab("payment");setMessage("")}} className={`flex shrink-0 items-center gap-2 rounded-t-[14px] border-b-2 px-4 py-3 text-sm font-semibold transition ${activeTab==="payment"?"border-[#0758e9] text-[#0758e9]":"border-transparent text-slate-500 hover:text-slate-800 dark:hover:text-slate-200"}`}><MessageCircle className="h-4 w-4"/>اتصال WhatsApp للدفع</button><button type="button" onClick={()=>{setActiveTab("support");setMessage("")}} className={`flex shrink-0 items-center gap-2 rounded-t-[14px] border-b-2 px-4 py-3 text-sm font-semibold transition ${activeTab==="support"?"border-[#0758e9] text-[#0758e9]":"border-transparent text-slate-500 hover:text-slate-800 dark:hover:text-slate-200"}`}><Headphones className="h-4 w-4"/>معلومات التواصل والدعم</button>{isMasterAdmin&&<button type="button" onClick={()=>{setActiveTab("hosting");setMessage("")}} className={`flex shrink-0 items-center gap-2 rounded-t-[14px] border-b-2 px-4 py-3 text-sm font-semibold transition ${activeTab==="hosting"?"border-[#0758e9] text-[#0758e9]":"border-transparent text-slate-500 hover:text-slate-800 dark:hover:text-slate-200"}`}><Globe className="h-4 w-4"/>الوصول للمخدم المحلي</button>}</div></div>
   {activeTab==="hosting"&&isMasterAdmin?<LocalHostingSettings/>:loading?<div className="p-8"><ProjectLoading>جارٍ تحميل الإعدادات...</ProjectLoading></div>:activeTab==="payment"?<div className="grid gap-5 p-6 md:grid-cols-2">
    <label className="text-xs font-medium text-slate-600 dark:text-slate-300">اسم جهة التواصل<ProjectInput className="mt-2" name="contact_name" autoComplete="organization" maxLength={80} value={form.contact_name} onChange={e=>set("contact_name",e.target.value)} placeholder="Radius Lord"/></label>
    <label className="text-xs font-medium text-slate-600 dark:text-slate-300">رقم WhatsApp الدولي<ProjectInput className="mt-2" type="tel" name="whatsapp_number" autoComplete="tel" inputMode="numeric" maxLength={15} pattern="[1-9][0-9]{6,14}" dir="ltr" value={form.whatsapp_number} onChange={e=>setWhatsapp(e.target.value)} placeholder="9639XXXXXXXX"/><span className="mt-2 block text-[10px] font-normal text-slate-400">أرقام إنكليزية فقط، من 7 إلى 15 رقمًا بصيغة دولية ومن دون + أو مسافات.</span></label>
    <label className="text-xs font-medium text-slate-600 dark:text-slate-300 md:col-span-2">نص زر التواصل<ProjectInput className="mt-2" name="whatsapp_button_text" maxLength={100} value={form.whatsapp_button_text} onChange={e=>set("whatsapp_button_text",e.target.value)} placeholder="التواصل عبر واتساب لإتمام الدفع"/></label>
    <label className="space-y-2 md:col-span-2"><span className="text-sm font-semibold">قالب رسالة WhatsApp</span><InputGroup className="rounded-[14px]"><InputGroupTextarea maxLength={1000} className="min-h-28" value={form.whatsapp_message_template} onChange={e=>set("whatsapp_message_template",e.target.value)}/></InputGroup><span className="text-xs text-slate-500">استخدم <bdi>{"{{payment_code}}"}</bdi> داخل النص ليتم استبداله بكود الدفع تلقائيًا.</span></label>
    <label className="space-y-2 md:col-span-2"><span className="text-sm font-semibold">تعليمات الدفع</span><InputGroup className="rounded-[14px]"><InputGroupTextarea maxLength={1500} className="min-h-24" value={form.payment_instructions} onChange={e=>set("payment_instructions",e.target.value)} placeholder="تعليمات تظهر للعميل قبل التواصل..."/></InputGroup></label>
    <div className="md:col-span-2 flex items-center justify-between rounded-2xl border border-slate-200/80 p-4 dark:border-white/10"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-green-500"/><div><div className="text-sm font-bold">تفعيل الدفع عبر WhatsApp</div><div className="text-xs text-slate-500">عند تعطيله لن يظهر زر التواصل للعميل.</div></div></div><button type="button" onClick={()=>set("whatsapp_enabled",!form.whatsapp_enabled)} className={`relative h-7 w-12 rounded-full transition ${form.whatsapp_enabled?"bg-green-500":"bg-slate-300 dark:bg-slate-700"}`} aria-label="تفعيل واتساب"><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition-all ${form.whatsapp_enabled?"right-6":"right-1"}`}/></button></div>
   </div>:<div className="grid gap-5 p-6 md:grid-cols-2"><div className="md:col-span-2"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[14px] bg-blue-50 text-[#0758e9] dark:bg-blue-500/10"><Headphones className="h-5 w-5"/></span><div><h2 className="text-sm font-bold text-slate-900 dark:text-white">معلومات التواصل والدعم</h2><p className="text-xs text-slate-500">بيانات التواصل العامة التي يمكن عرضها للعملاء عند الحاجة إلى الدعم.</p></div></div></div><label className="text-xs font-medium text-slate-600 dark:text-slate-300">البريد الإلكتروني للدعم<ProjectInput className="mt-2" type="email" name="support_email" autoComplete="email" maxLength={160} dir="ltr" value={form.support_email} onChange={e=>set("support_email",e.target.value)} placeholder="support@example.com"/></label><label className="text-xs font-medium text-slate-600 dark:text-slate-300">رقم التواصل الأساسي<ProjectInput className="mt-2" type="tel" name="support_phone_primary" autoComplete="tel" inputMode="numeric" maxLength={15} dir="ltr" value={form.support_phone_primary} onChange={e=>set("support_phone_primary",digits(e.target.value))} placeholder="9639XXXXXXXX"/></label><label className="text-xs font-medium text-slate-600 dark:text-slate-300">رقم تواصل إضافي<ProjectInput className="mt-2" type="tel" name="support_phone_secondary" inputMode="numeric" maxLength={15} dir="ltr" value={form.support_phone_secondary} onChange={e=>set("support_phone_secondary",digits(e.target.value))} placeholder="اختياري"/></label><div className="flex items-center gap-2 self-end pb-3 text-xs text-slate-400"><Mail className="h-4 w-4"/><Phone className="h-4 w-4"/><span>استخدم الصيغة الدولية للأرقام من دون + أو مسافات.</span></div></div>}
   {activeTab!=="hosting"&&<div className="flex items-center justify-between gap-3 border-t border-slate-200/70 px-6 py-4 dark:border-white/10"><span className={`text-sm ${message.startsWith("تم ")?"text-green-600 dark:text-green-400":"text-red-500"}`}>{message}</span><button type="button" disabled={loading||saving} onClick={save} className="inline-flex h-11 items-center gap-2 rounded-2xl bg-[#0758e9] px-5 text-sm font-bold text-white shadow-sm transition hover:bg-[#064fd1] disabled:opacity-50"><Save className="h-4 w-4"/>{saving?"جارٍ الحفظ...":"حفظ الإعدادات"}</button></div>}
  </section>
  {activeTab!=="hosting"&&<div className="flex items-start gap-3 rounded-[22px] border border-blue-200/70 bg-blue-50/70 p-4 text-sm text-blue-900 dark:border-blue-500/20 dark:bg-blue-500/10 dark:text-blue-200"><Settings2 className="mt-0.5 h-5 w-5 shrink-0"/><p>هذه البيانات عامة على منصة Radius Lord وليست مرتبطة بخطة محددة. كود الدفع والخطة والإجمالي سيضافان إلى رسالة العميل عند إنشاء طلب الدفع.</p></div>}
 </div>;
}
