"use client";
import { useEffect,useState,FormEvent } from "react";
import { ArrowRight,Check,Cloud,PackagePlus,Server } from "lucide-react";
import { useRouter } from "next/navigation";
import ProjectDropdown from "@/components/ui/project-dropdown";
const STATUS=[{value:"active",label:"نشطة"},{value:"inactive",label:"غير نشطة"},{value:"disabled",label:"معطلة"}];
type Currency={id:number;code:string;nameAr:string;symbol:string};type Deployment={id:number;code:string;nameAr:string;description:string};
type Option={deploymentTypeId:number;price:number;setupFee:number;isDefault:boolean;status:"active"|"inactive"};
export default function AddPlanPage(){
 const router=useRouter();const [currencies,setCurrencies]=useState<Currency[]>([]),[types,setTypes]=useState<Deployment[]>([]),[options,setOptions]=useState<Option[]>([]);
 const [form,setForm]=useState({name:"",durationMonths:1,maxTenants:1,maxSubscribers:0,maxNas:0,currencyId:0,description:"",isFeatured:false,status:"active"});const [saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/admin/payment-plans/currencies",{credentials:"include"}).then(r=>r.json()),fetch("/api/admin/payment-plans/deployment-types",{credentials:"include"}).then(r=>r.json())]).then(([c,d])=>{setCurrencies(c.currencies??[]);setTypes(d.deploymentTypes??[]);if(c.currencies?.[0])setForm(x=>({...x,currencyId:c.currencies[0].id}))}).catch(()=>setMessage("تعذر تحميل إعدادات الخطط."))},[]);
 const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const enabled=(id:number)=>options.some(o=>o.deploymentTypeId===id);
 const toggle=(id:number)=>setOptions(old=>old.some(o=>o.deploymentTypeId===id)?old.filter(o=>o.deploymentTypeId!==id):[...old,{deploymentTypeId:id,price:0,setupFee:0,isDefault:old.length===0,status:"active"}]);
 const patch=(id:number,key:keyof Option,value:any)=>setOptions(old=>old.map(o=>o.deploymentTypeId===id?{...o,[key]:value,...(key==="isDefault"&&value?{}:{})}:o).map(o=>key==="isDefault"&&value&&o.deploymentTypeId!==id?{...o,isDefault:false}:o));
 async function submit(e:FormEvent){e.preventDefault();if(!options.length){setMessage("اختر نوع استضافة واحدًا على الأقل.");return}setSaving(true);setMessage("");const r=await fetch("/api/admin/payment-plans",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({...form,deploymentOptions:options})});const d=await r.json();setSaving(false);if(!r.ok){setMessage(d.message??"تعذر إنشاء الخطة.");return}router.push("/Dashboard/plans");router.refresh();}
 return <div className="mx-auto max-w-4xl space-y-4" dir="rtl">
 <section className="rl-surface rounded-[22px] bg-white p-4 dark:bg-[#0d243b]"><div className="flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-semibold"><PackagePlus className="h-5 w-5 text-[#0758e9]"/>إضافة خطة اشتراك</h2><p className="mt-1 text-xs text-slate-500">حدد موارد الخطة ثم طرق الاستضافة وأسعار كل طريقة.</p></div><button onClick={()=>router.push("/Dashboard/plans")} className="flex items-center gap-2 rounded-[14px] border border-[#bfd4ea] px-3 py-2 text-xs text-[#0758e9]"><ArrowRight className="h-4 w-4"/>عرض الخطط</button></div></section>
 <form onSubmit={submit} className="space-y-4">
  <section className="rl-surface rounded-[22px] bg-[#e7eef6] p-5 dark:bg-[#243445]"><h3 className="mb-4 text-sm font-semibold">بيانات الخطة</h3><div className="grid gap-4 sm:grid-cols-2">{[["name","اسم الخطة","text"],["durationMonths","المدة بالأشهر","number"],["maxTenants","عدد الشبكات","number"],["maxSubscribers","إجمالي المشتركين","number"],["maxNas","إجمالي NAS","number"]].map(([k,l,t])=><label key={k} className="text-xs text-slate-500">{l}<input required type={t} min={t==="number"?0:undefined} value={(form as any)[k]} onChange={e=>set(k,t==="number"?Number(e.target.value):e.target.value)} className="mt-1 h-11 w-full rounded-[14px] border border-[#d7e3ef] bg-[#f9fbfe] px-3 text-sm text-slate-700 outline-none focus:border-[#6aaeff] dark:border-white/10 dark:bg-[#38363c] dark:text-slate-200"/></label>)}<label className="text-xs text-slate-500">العملة<ProjectDropdown className="mt-1" value={String(form.currencyId||"")} onChange={v=>set("currencyId",Number(v))} options={currencies.map(c=>({value:String(c.id),label:`${c.code} — ${c.nameAr}`}))}/></label><label className="text-xs text-slate-500">الحالة<ProjectDropdown className="mt-1" value={form.status} onChange={v=>set("status",v)} options={STATUS}/></label><label className="sm:col-span-2 text-xs text-slate-500">الوصف<textarea value={form.description} onChange={e=>set("description",e.target.value)} className="mt-1 min-h-24 w-full rounded-[14px] border border-[#d7e3ef] bg-[#f9fbfe] p-3 outline-none dark:border-white/10 dark:bg-[#38363c]"/></label><label className="sm:col-span-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={form.isFeatured} onChange={e=>set("isFeatured",e.target.checked)}/>تمييز هذه الخطة في عرض الأسعار</label></div><div className="mt-2 text-[11px] text-slate-400">القيمة 0 للمشتركين وNAS تعني غير محدود.</div></section>
  <section className="rl-surface rounded-[22px] bg-white p-5 dark:bg-[#0d243b]"><div className="mb-4"><h3 className="text-sm font-semibold">خيارات الاستضافة</h3><p className="mt-1 text-[11px] text-slate-400">يمكن تفعيل أكثر من طريقة استضافة للخطة، ولكل طريقة سعر ورسوم تأسيس مستقلة بنفس عملة الخطة.</p></div><div className="grid gap-3">{types.map(t=>{const o=options.find(x=>x.deploymentTypeId===t.id);return <div key={t.id} className={`rounded-[18px] border p-4 transition ${o?"border-[#7db0ed] bg-[#f5f9ff] dark:bg-white/[.05]":"border-[#d7e3ef] dark:border-white/10"}`}><div className="flex items-start gap-3"><button type="button" onClick={()=>toggle(t.id)} className={`mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-[8px] border ${o?"border-[#0758e9] bg-[#0758e9] text-white":"border-slate-300"}`}>{o&&<Check className="h-4 w-4"/>}</button><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-sm font-semibold">{t.code==="on_premise"?<Server className="h-4 w-4 text-[#397bd5]"/>:<Cloud className="h-4 w-4 text-[#397bd5]"/>}{t.nameAr}</div><p className="mt-1 text-[11px] text-slate-400">{t.description}</p>{o&&<div className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><Number label="السعر" value={o.price} onChange={v=>patch(t.id,"price",v)}/><Number label="رسوم التأسيس" value={o.setupFee} onChange={v=>patch(t.id,"setupFee",v)}/><button type="button" onClick={()=>patch(t.id,"isDefault",true)} className={`self-end h-11 rounded-[13px] border px-3 text-xs ${o.isDefault?"border-[#0758e9] bg-[#e9f2ff] text-[#0758e9]":"border-[#d7e3ef] text-slate-500"}`}>{o.isDefault?"الافتراضية":"تعيين افتراضية"}</button></div>}</div></div></div>})}</div></section>
  {message&&<div className="rounded-xl bg-red-50 p-3 text-xs text-red-600 dark:bg-red-500/10">{message}</div>}<div className="flex justify-end gap-2"><button type="button" onClick={()=>router.push("/Dashboard/plans")} className="rounded-[14px] border px-4 py-2.5 text-xs">إلغاء</button><button disabled={saving} className="rounded-[14px] bg-[#0758e9] px-5 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{saving?"جارٍ الحفظ...":"إنشاء الخطة"}</button></div>
 </form></div>
}
function Number({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="text-[11px] text-slate-400">{label}<input type="number" min="0" step=".01" value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-1 h-11 w-full rounded-[13px] border border-[#d7e3ef] bg-white px-3 text-sm outline-none dark:border-white/10 dark:bg-[#38363c]"/></label>}
