"use client";
import { useEffect,useRef,useState,FormEvent } from "react";
import { ArrowRight,Check,Cloud,Server } from "lucide-react";
import { useRouter } from "next/navigation";
import ProjectDropdown from "@/components/ui/project-dropdown";
const STATUS=[{value:"active",label:"نشطة",dotClassName:"bg-emerald-500"},{value:"inactive",label:"غير نشطة",dotClassName:"bg-amber-400"},{value:"disabled",label:"معطلة",dotClassName:"bg-red-500"}];
const normalizeDigits=(value:string)=>value.replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d).toString()).replace(/[۰-۹]/g,d=>"۰۱۲۳۴۵۶۷۸۹".indexOf(d).toString());
const toNumber=(value:string)=>Number(normalizeDigits(value).replace(",",".").trim());
const integerOnly=(value:string)=>normalizeDigits(value).replace(/\D/g,"");
const decimalOnly=(value:string)=>{const v=normalizeDigits(value).replace(",",".").replace(/[^0-9.]/g,"");const [a,...b]=v.split(".");return b.length?`${a}.${b.join("")}`:a};
type Currency={id:number;code:string;nameAr:string;symbol:string};type Deployment={id:number;code:string;nameAr:string;description:string};
type Option={deploymentTypeId:number;price:string;isDefault:boolean;status:"active"|"inactive"};
export default function AddPlanPage(){
 const router=useRouter();const formRef=useRef<HTMLFormElement|null>(null);const hostingRef=useRef<HTMLElement|null>(null);const actionsRef=useRef<HTMLDivElement|null>(null);const autoAdvancedRef=useRef(false);const [currencies,setCurrencies]=useState<Currency[]>([]),[types,setTypes]=useState<Deployment[]>([]),[options,setOptions]=useState<Option[]>([]);
 const [form,setForm]=useState({name:"",durationMonths:"1",price:"",maxSubscribers:"",maxNas:"",currencyId:0,description:"",isFeatured:false,status:"active"});const [remoteAccess,setRemoteAccess]=useState({enabled:false,price:""});const [saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/admin/payment-plans/currencies",{credentials:"include"}).then(r=>r.json()),fetch("/api/admin/payment-plans/deployment-types",{credentials:"include"}).then(r=>r.json())]).then(([c,d])=>{setCurrencies(c.currencies??[]);setTypes(d.deploymentTypes??[]);if(c.currencies?.[0])setForm(x=>({...x,currencyId:c.currencies[0].id}))}).catch(()=>setMessage("تعذر تحميل إعدادات الخطط."))},[]);
 const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const enabled=(id:number)=>options.some(o=>o.deploymentTypeId===id);
 const scrollSlow=(node:HTMLElement|null,duration=1200)=>{const scroller=formRef.current?.closest(".workspace-scroll") as HTMLElement|null;if(!node||!scroller)return;const start=scroller.scrollTop,target=Math.max(0,node.getBoundingClientRect().top-scroller.getBoundingClientRect().top+start-24),distance=target-start,started=performance.now();const tick=(now:number)=>{const p=Math.min((now-started)/duration,1),eased=.5-Math.cos(Math.PI*p)/2;scroller.scrollTop=start+distance*eased;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)};
 const topComplete=form.name.trim()!==""&&Number.isInteger(toNumber(form.durationMonths))&&toNumber(form.durationMonths)>=1&&form.maxSubscribers.trim()!==""&&form.maxNas.trim()!==""&&form.currencyId>0&&form.price.trim()!==""&&Number.isFinite(toNumber(form.price))&&toNumber(form.price)>=0;
 const advanceAfterPrice=()=>{if(topComplete&&!autoAdvancedRef.current){autoAdvancedRef.current=true;setMessage("");setTimeout(()=>scrollSlow(hostingRef.current),180)}};
 useEffect(()=>{if(!topComplete){autoAdvancedRef.current=false;return}const timer=window.setTimeout(()=>advanceAfterPrice(),450);return()=>window.clearTimeout(timer)},[topComplete,form.price]);
 useEffect(()=>{if(!remoteAccess.enabled||remoteAccess.price.trim()===""||!Number.isFinite(toNumber(remoteAccess.price))||toNumber(remoteAccess.price)<0)return;const timer=window.setTimeout(()=>scrollSlow(actionsRef.current,1300),500);return()=>window.clearTimeout(timer)},[remoteAccess.enabled,remoteAccess.price]);
 const toggle=(id:number)=>{const selecting=!enabled(id);setOptions(selecting?[{deploymentTypeId:id,price:"",isDefault:true,status:"active"}]:[]);if(selecting)setTimeout(()=>scrollSlow(actionsRef.current,1300),260)};
 const patch=(id:number,key:keyof Option,value:any)=>setOptions(old=>old.map(o=>o.deploymentTypeId===id?{...o,[key]:value,...(key==="isDefault"&&value?{}:{})}:o).map(o=>key==="isDefault"&&value&&o.deploymentTypeId!==id?{...o,isDefault:false}:o));
 async function submit(e:FormEvent){e.preventDefault();const durationMonths=toNumber(form.durationMonths),price=toNumber(form.price),maxSubscribers=form.maxSubscribers.trim()===""?0:toNumber(form.maxSubscribers),maxNas=form.maxNas.trim()===""?0:toNumber(form.maxNas);if(!Number.isInteger(durationMonths)||durationMonths<1){setMessage("أدخل مدة صحيحة للخطة، شهر واحد على الأقل.");return}if(!Number.isFinite(price)||price<0){setMessage("أدخل سعرًا صالحًا للخطة.");return}if(![maxSubscribers,maxNas].every(v=>Number.isInteger(v)&&v>=0)){setMessage("تحقق من أعداد المشتركين وNAS.");return}if(!options.length){setMessage("اختر نوع استضافة واحدًا على الأقل.");return}const local=types.find(t=>t.code==="on_premise");const addons=remoteAccess.enabled&&local&&enabled(local.id)?[{deploymentTypeId:local.id,code:"remote_access",nameAr:"الوصول من أي مكان",nameEn:"Remote Access",description:"إتاحة الوصول إلى Radius Lord من خارج الشبكة المحلية.",price:Number(remoteAccess.price||0),status:"active"}]:[];setSaving(true);setMessage("");const r=await fetch("/api/admin/payment-plans",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({...form,durationMonths,price,maxTenants:1,maxSubscribers,maxNas,deploymentOptions:options.map(o=>({...o,price})),addons})});const d=await r.json();setSaving(false);if(!r.ok){setMessage(d.message??"تعذر إنشاء الخطة.");return}router.push("/Dashboard/plans?created=1");router.refresh();}
 return <div className="mx-auto max-w-6xl space-y-3" dir="rtl">
 <div className="flex justify-end"><button type="button" onClick={()=>router.push("/Dashboard/plans")} className="flex items-center gap-2 rounded-[14px] border border-[#bfd4ea] bg-white/75 px-3 py-2 text-xs font-medium text-[#0758e9] transition hover:bg-white dark:border-white/10 dark:bg-white/[.04]"><ArrowRight className="h-4 w-4"/>عرض الخطط</button></div>
 <form ref={formRef} onSubmit={submit} onKeyDown={e=>{if(e.key!=="Enter"||e.shiftKey)return;const target=e.target as HTMLElement;if(target.tagName==="TEXTAREA"||target.getAttribute("role")==="button")return;const fields=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('input:not([type="checkbox"]):not([type="hidden"]),button[role="combobox"],textarea')).filter(el=>!el.hasAttribute("disabled")&&el.offsetParent!==null);const index=fields.indexOf(target);if(index>=0&&index<fields.length-1){e.preventDefault();fields[index+1].focus()}}} className="relative space-y-3">
  <div className="rl-surface overflow-hidden rounded-[22px] bg-white shadow-[0_8px_24px_rgba(58,84,112,.07)] dark:bg-[#0d243b]">
  <section className="p-4 sm:p-5"><div className="mb-3"><h3 className="text-base font-semibold text-[#17386d] dark:text-slate-100">بيانات الخطة</h3><p className="mt-1 text-xs text-slate-400">أدخل البيانات الأساسية وحدود الموارد الخاصة بالخطة.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["name","اسم الخطة","text"],["durationMonths","المدة بالأشهر","number"],["maxSubscribers","إجمالي المشتركين","number"],["maxNas","إجمالي NAS","number"]].map(([k,l,t])=><label key={k} className="text-xs font-medium text-slate-600 dark:text-slate-300">{l}<input required type={t} min={t==="number"?(k==="durationMonths"?1:0):undefined} value={(form as any)[k]} inputMode={t==="number"?"numeric":undefined} onChange={e=>set(k,t==="number"?integerOnly(e.target.value):e.target.value)} className="allow-text-selection mt-2 h-12 w-full rounded-[14px] border border-[#d7e3ef] bg-[#f9fbfe] px-3.5 text-sm text-slate-700 outline-none transition focus:border-[#2382ef] focus:bg-white focus:ring-4 focus:ring-[#2382ef]/10 dark:border-white/10 dark:bg-[#26384a] dark:text-slate-100 dark:focus:bg-[#2b4055]"/></label>)}<label className="text-xs text-slate-500">العملة<ProjectDropdown className="mt-1" value={String(form.currencyId||"")} onChange={v=>set("currencyId",Number(v))} options={currencies.map(c=>({value:String(c.id),label:`${c.symbol||c.code}  ${c.code} — ${c.nameAr}`}))}/></label><label className="text-xs text-slate-500">الحالة<ProjectDropdown className="mt-1" value={form.status} onChange={v=>set("status",v)} options={STATUS}/></label><div className="sm:col-span-2 lg:col-span-3 border-t border-[#e2ebf4] pt-3 dark:border-white/10"><PriceInput label="سعر الخطة" value={form.price} currency={currencies.find(c=>c.id===form.currencyId)?.symbol||currencies.find(c=>c.id===form.currencyId)?.code||""} onChange={v=>set("price",v)} onComplete={advanceAfterPrice}/></div><label className="sm:col-span-2 lg:col-span-3 text-xs font-medium text-slate-600 dark:text-slate-300">الوصف<textarea value={form.description} onChange={e=>set("description",e.target.value)} className="allow-text-selection mt-2 min-h-20 w-full resize-y rounded-[14px] border border-[#d7e3ef] bg-[#f9fbfe] p-3.5 text-sm outline-none transition focus:border-[#2382ef] focus:bg-white focus:ring-4 focus:ring-[#2382ef]/10 dark:border-white/10 dark:bg-[#26384a] dark:focus:bg-[#2b4055]"/></label><div className="sm:col-span-2 lg:col-span-3 flex flex-wrap items-center justify-between gap-3 border-t border-[#e2ebf4] pt-3 dark:border-white/10"><label className="flex items-center gap-2 text-xs font-medium text-slate-600 dark:text-slate-300"><input type="checkbox" checked={form.isFeatured} onChange={e=>set("isFeatured",e.target.checked)} className="h-4 w-4 rounded border-[#b9cbe0] accent-[#0758e9]"/>تمييز هذه الخطة في عرض الأسعار</label><span className="text-[11px] text-slate-400">القيمة 0 للمشتركين وNAS تعني غير محدود.</span></div></div></section>
  <section ref={hostingRef} id="hosting-options" className="scroll-mt-24 border-t border-[#e2ebf4] p-4 sm:p-5 dark:border-white/10">
   <div className="mb-4"><h3 className="text-base font-semibold text-[#17386d] dark:text-slate-100">خيارات الاستضافة</h3><p className="mt-1 text-[11px] text-slate-400">حدد طرق تشغيل الخطة المتاحة للعميل. السعر الأساسي واحد ولا يتغير حسب طريقة الاستضافة.</p></div>
   <div className="grid gap-3 md:grid-cols-2">{types.map(t=>{const o=options.find(x=>x.deploymentTypeId===t.id);const local=t.code==="on_premise";return <div key={t.id} className={`rounded-[18px] border p-4 transition-all duration-300 ${local&&o?"md:col-span-2":""} ${o?"border-[#79b2ef] bg-[#f4f9ff] dark:bg-[#132c46]":"border-[#d7e3ef] dark:border-white/10"}`}>
    {local&&o?<div className="grid gap-4 md:grid-cols-2 md:items-stretch">
      <div className="flex min-w-0 flex-col">
       <button type="button" onClick={()=>toggle(t.id)} className="flex w-full items-start gap-3 text-right"><span className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-[8px] border border-[#0758e9] bg-[#0758e9] text-white"><Check className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-sm font-semibold"><Server className="h-4 w-4 text-[#0758e9]"/>{t.nameAr}</span><span className="mt-1 block text-[11px] text-slate-400">{t.description}</span></span></button>
       <div className="mt-4"><button type="button" onClick={()=>patch(t.id,"isDefault",true)} className={`h-9 rounded-[12px] border px-3 text-[11px] ${o.isDefault?"border-[#0758e9] bg-[#e9f2ff] text-[#0758e9] dark:bg-[#163a60]":"border-[#d7e3ef] text-slate-500 dark:border-white/10 dark:text-slate-300"}`}>{o.isDefault?"الافتراضية":"تعيين افتراضية"}</button></div>
      </div>
      <div className="rounded-[16px] border border-[#cfe0f0] bg-white/65 p-4 dark:border-white/10 dark:bg-white/[.035]">
       <div className="mb-3"><div className="text-xs font-semibold text-[#17386d] dark:text-slate-100">إضافات الاستضافة المحلية</div><p className="mt-1 text-[10px] text-slate-400">خدمات اختيارية خاصة بهذه الاستضافة.</p></div>
       <div className="rounded-[14px] border border-[#d7e3ef] bg-white/70 p-3 dark:border-white/10 dark:bg-white/[.03]"><div className="flex items-start gap-3"><button type="button" onClick={()=>setRemoteAccess(x=>({...x,enabled:!x.enabled}))} className={`mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-[8px] border ${remoteAccess.enabled?"border-[#0758e9] bg-[#0758e9] text-white":"border-slate-300 dark:border-white/20"}`}>{remoteAccess.enabled&&<Check className="h-4 w-4"/>}</button><div className="min-w-0 flex-1"><div className="text-sm font-semibold">الوصول من أي مكان</div><p className="mt-1 text-[11px] text-slate-400">إتاحة الوصول إلى Radius Lord من خارج الشبكة المحلية.</p>{remoteAccess.enabled&&<div className="mt-3"><PriceInput label="السعر الإضافي" value={remoteAccess.price} currency={currencies.find(c=>c.id===form.currencyId)?.symbol||currencies.find(c=>c.id===form.currencyId)?.code||""} onChange={price=>setRemoteAccess(x=>({...x,price}))}/></div>}</div></div></div>
      </div>
     </div>:<>
      <button type="button" onClick={()=>toggle(t.id)} className="flex w-full items-start gap-3 text-right"><span className={`mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-[8px] border ${o?"border-[#0758e9] bg-[#0758e9] text-white":"border-slate-300"}`}>{o&&<Check className="h-4 w-4"/>}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-sm font-semibold">{local?<Server className="h-4 w-4 text-[#0758e9]"/>:<Cloud className="h-4 w-4 text-[#0758e9]"/>}{t.nameAr}</span><span className="mt-1 block text-[11px] text-slate-400">{t.description}</span></span></button>
      {o&&<div className="mt-3"><button type="button" onClick={()=>patch(t.id,"isDefault",true)} className={`h-9 rounded-[12px] border px-3 text-[11px] ${o.isDefault?"border-[#0758e9] bg-[#e9f2ff] text-[#0758e9] dark:bg-[#163a60]":"border-[#d7e3ef] text-slate-500 dark:border-white/10 dark:text-slate-300"}`}>{o.isDefault?"الافتراضية":"تعيين افتراضية"}</button></div>}
     </>}
   </div>})}</div>
  </section>
  </div>
  {message&&<div className="rounded-xl bg-red-50 p-3 text-xs text-red-600 dark:bg-red-500/10">{message}</div>}<div ref={actionsRef} className="scroll-mt-24 flex justify-end gap-2"><button type="button" onClick={()=>router.push("/Dashboard/plans")} className="rounded-[14px] border px-4 py-2.5 text-xs">إلغاء</button><button disabled={saving} className="rounded-[14px] bg-[#0758e9] px-5 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{saving?"جارٍ الحفظ...":"إنشاء الخطة"}</button></div>
 </form></div>
}
function PriceInput({label,value,onChange,currency="",onComplete}:{label:string;value:string;onChange:(v:string)=>void;currency?:string;onComplete?:()=>void}){return <label className="block text-[11px] font-medium text-slate-500">{label}<div className="relative mt-2 max-w-sm"><input inputMode="decimal" value={value} onBlur={onComplete} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();onComplete?.()}}} onChange={e=>onChange(decimalOnly(e.target.value))} className="allow-text-selection h-12 w-full rounded-[14px] border border-[#d7e3ef] bg-white px-3.5 pl-16 text-sm text-slate-700 outline-none transition focus:border-[#2382ef] focus:ring-4 focus:ring-[#2382ef]/10 dark:border-white/10 dark:bg-[#26384a] dark:text-slate-100"/>{currency&&<span className="pointer-events-none absolute inset-y-0 left-3 flex items-center border-r border-[#d7e3ef] pr-3 text-xs font-semibold text-[#0758e9] dark:border-white/10">{currency}</span>}</div></label>}
