"use client";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { ArrowRight, PackagePlus } from "lucide-react";
import ProjectDropdown from "@/components/ui/project-dropdown";
import { CURRENCY_OPTIONS } from "@/lib/currencies";

const PLAN_STATUS_OPTIONS=[{value:"active",label:"نشطة"},{value:"inactive",label:"غير نشطة"},{value:"disabled",label:"معطلة"}];

export default function AddPlanPage(){
 const router=useRouter();
 const [form,setForm]=useState({name:"",durationMonths:1,maxTenants:1,maxSubscribers:0,maxNas:0,price:0,currency:"USD",description:"",isFeatured:false,status:"active"});
 const [saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");const r=await fetch("/api/admin/payment-plans",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify(form)});const d=await r.json();setSaving(false);if(!r.ok){setMessage(d.message??"تعذر إنشاء الخطة.");return}router.push("/Dashboard/plans");router.refresh();}
 return <div className="mx-auto max-w-4xl space-y-4" dir="rtl">
  <section className="rl-surface rounded-[22px] bg-white p-4 dark:bg-[#0d243b]"><div className="flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-semibold"><PackagePlus className="h-5 w-5 text-[#0758e9]"/>إضافة خطة اشتراك</h2><p className="mt-1 text-xs text-slate-500">إنشاء خطة جديدة وتحديد موارد Customer المسموحة.</p></div><button onClick={()=>router.push("/Dashboard/plans")} className="flex items-center gap-2 rounded-[14px] border border-[#bfd4ea] px-3 py-2 text-xs text-[#0758e9]"><ArrowRight className="h-4 w-4"/>عرض الخطط</button></div></section>
  <form onSubmit={submit} className="rl-surface rounded-[22px] bg-[#e7eef6] p-5 dark:bg-[#243445]"><div className="grid gap-4 sm:grid-cols-2">{[["name","اسم الخطة","text"],["price","السعر","number"],["durationMonths","المدة بالأشهر","number"],["maxTenants","عدد الشبكات","number"],["maxSubscribers","إجمالي المشتركين","number"],["maxNas","إجمالي NAS","number"]].map(([k,l,t])=><label key={k} className="text-xs text-slate-500">{l}<input required type={t} min={t==="number"?0:undefined} step={k==="price"?"0.01":"1"} value={(form as any)[k]} onChange={e=>set(k,t==="number"?Number(e.target.value):e.target.value)} className="mt-1 h-11 w-full rounded-[14px] border border-[#d7e3ef] bg-[#f9fbfe] px-3 text-sm text-slate-700 outline-none focus:border-[#6aaeff] dark:border-white/10 dark:bg-[#38363c] dark:text-slate-200"/></label>)}<label className="text-xs text-slate-500">العملة<ProjectDropdown className="mt-1" value={form.currency} onChange={v=>set("currency",v)} options={CURRENCY_OPTIONS}/></label><label className="text-xs text-slate-500">الحالة<ProjectDropdown className="mt-1" value={form.status} onChange={v=>set("status",v)} options={PLAN_STATUS_OPTIONS}/></label><label className="sm:col-span-2 text-xs text-slate-500">الوصف<textarea value={form.description} onChange={e=>set("description",e.target.value)} className="mt-1 min-h-24 w-full rounded-[14px] border border-[#d7e3ef] bg-[#f9fbfe] p-3 outline-none focus:border-[#6aaeff] dark:border-white/10 dark:bg-[#38363c]"/></label><label className="sm:col-span-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={form.isFeatured} onChange={e=>set("isFeatured",e.target.checked)}/>تمييز هذه الخطة في عرض الأسعار</label></div><div className="mt-2 text-[11px] text-slate-400">القيمة 0 للمشتركين وNAS تعني غير محدود.</div>{message&&<div className="mt-3 rounded-xl bg-red-50 p-3 text-xs text-red-600 dark:bg-red-500/10">{message}</div>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>router.push("/Dashboard/plans")} className="rounded-[14px] border px-4 py-2.5 text-xs">إلغاء</button><button disabled={saving} className="rounded-[14px] bg-[#0758e9] px-5 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{saving?"جارٍ الحفظ...":"إنشاء الخطة"}</button></div></form>
 </div>
}