import {randomBytes,createHash} from 'crypto';
import {readFileSync} from 'fs';
import {join} from 'path';
import mysql from 'mysql2/promise';
import {db} from '../config/db';
import {encryptProvisioningSecret,decryptProvisioningSecret} from '../services/provisioning-secrets.service';
import {splitTenantTemplate} from '../services/tenant-template.service';
const VERSION='tenant-20261007-v1';
class ProvisioningFailure extends Error{constructor(public code:string){super(code);}}
// Dedicated sequential worker: no production provisioning starts just by launching API.
async function main(){const central=await db.pool.getConnection();let admin:mysql.Connection|undefined,app:mysql.Connection|undefined,radius:mysql.Connection|undefined,job:any,currentStep='preflight',locked=false;
 const lockName='radius-lord:database-provisioner';
 async function audit(event:string){const [ids]:any=await central.query("SELECT (SELECT id FROM audit_actions WHERE code='UPDATE' AND is_active=1 LIMIT 1) action_id,(SELECT id FROM audit_entity_types WHERE code='PROVISIONING_JOB' AND is_active=1 LIMIT 1) entity_type_id");if(!ids[0]?.action_id||!ids[0]?.entity_type_id)throw new ProvisioningFailure('AUDIT_DICTIONARY_MISSING');await central.query('INSERT INTO central_audit_logs (admin_id,tenant_id,action_id,entity_type_id,entity_id,description,metadata) VALUES (NULL,?,?,?,?,?,?)',[job.tenant_id,ids[0].action_id,ids[0].entity_type_id,job.id,'تنفيذ مرحلة تجهيز قاعدة الشبكة',JSON.stringify({actorKind:'system',event,jobId:job.id,step:currentStep,requestedByMasterAdminId:job.requested_by_master_admin_id})]);}
 async function done(code:string){const [r]:any=await central.query("SELECT status FROM environment_provisioning_steps WHERE job_id=? AND step_code=?",[job.id,code]);return r[0]?.status==='success';}
 async function step(code:string,operation:()=>Promise<void>){currentStep=code;await central.query('UPDATE environment_provisioning_jobs SET current_step=? WHERE id=?',[code,job.id]);if(await done(code))return;await central.query("INSERT INTO environment_provisioning_steps (job_id,step_code,status,attempt_count,started_at) VALUES (?,?,'running',1,CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE status='running',attempt_count=attempt_count+1,started_at=CURRENT_TIMESTAMP,error_code=NULL,error_message=NULL",[job.id,code]);await operation();await central.query("UPDATE environment_provisioning_steps SET status='success',finished_at=CURRENT_TIMESTAMP WHERE job_id=? AND step_code=?",[job.id,code]);await audit('step_success');}
 try{const [lock]:any=await central.query('SELECT GET_LOCK(?,0) acquired',[lockName]);if(!lock[0].acquired)return;locked=true;
 // The named connection lock fences all instances of this worker, including crashed/restarted jobs.
 const [jobs]:any=await central.query("SELECT * FROM environment_provisioning_jobs WHERE status IN ('queued','running') AND available_at<=CURRENT_TIMESTAMP ORDER BY id LIMIT 1");job=jobs[0];if(!job)return;
 const [scope]:any=await central.query("SELECT e.*,dt.code deployment_code,s.status subscription_status,p.status payment_status FROM tenant_environments e JOIN deployment_types dt ON dt.id=e.deployment_type_id JOIN subscriptions s ON s.id=? AND s.tenant_id=e.tenant_id JOIN payment_orders p ON p.id=? AND p.subscription_id=s.id AND p.tenant_id=e.tenant_id WHERE e.id=? AND e.archived_at IS NULL",[job.subscription_id,job.payment_order_id,job.environment_id]);if(!scope[0]||scope[0].subscription_status!=='pending'||!['paid','completed'].includes(scope[0].payment_status)||scope[0].status==='ready')throw new ProvisioningFailure('INVALID_PROVISIONING_SCOPE');
 await central.query("UPDATE environment_provisioning_jobs SET status='running',attempt_count=attempt_count+1,started_at=COALESCE(started_at,CURRENT_TIMESTAMP),error_code=NULL,error_message=NULL WHERE id=?",[job.id]);await central.query("UPDATE tenant_environments SET status='provisioning' WHERE id=?",[job.environment_id]);await audit('database_provisioning_started');
 if(scope[0].deployment_code!=='shared_cloud')throw new ProvisioningFailure('DEPLOYMENT_DRIVER_NOT_AVAILABLE');
 const clientHost=process.env.TENANT_DB_CLIENT_HOST||'';if(!clientHost||clientHost.length>255||/[\x00-\x20%_'"\\]/.test(clientHost))throw new ProvisioningFailure('TENANT_DB_CLIENT_HOST_REQUIRED');
 const template=readFileSync(join(__dirname,'../tenant-schema/create_tenant_database.sql'),'utf8'),digest=createHash('sha256').update(template).digest('hex');
 let [databases]:any=await central.query('SELECT * FROM tenant_databases WHERE tenant_id=?',[job.tenant_id]);let d=databases[0],server:any;
 await central.beginTransaction();try{if(d){const [servers]:any=await central.query("SELECT * FROM database_servers WHERE id=? AND archived_at IS NULL FOR UPDATE",[d.database_server_id]);server=servers[0];if(!server||server.status!=='active')throw new ProvisioningFailure('DATABASE_SERVER_UNAVAILABLE');}
 else{const [servers]:any=await central.query("SELECT ds.* FROM database_servers ds WHERE ds.status='active' AND ds.accepts_new_environments=1 AND ds.archived_at IS NULL AND ds.app_connection_budget>=4+(SELECT COALESCE(SUM(td.app_pool_limit),0) FROM tenant_databases td WHERE td.database_server_id=ds.id) AND ds.radius_connection_budget>=4+(SELECT COALESCE(SUM(td.radius_pool_limit),0) FROM tenant_databases td WHERE td.database_server_id=ds.id) ORDER BY ds.id LIMIT 1 FOR UPDATE");server=servers[0];if(!server)throw new ProvisioningFailure('NO_DATABASE_SERVER_CAPACITY');const token=randomBytes(8).toString('hex'),name=`rl_tenant_${job.tenant_id}_${token}`,a=`rla_${token}`,r=`rlr_${token}`;const [insert]:any=await central.query("INSERT INTO tenant_databases (tenant_id,database_server_id,db_host,db_port,db_name,db_username,db_password,app_password_encrypted,radius_username,radius_password_encrypted,status,credentials_state,app_pool_limit,radius_pool_limit) VALUES (?,?,?,?,?,?,'[encrypted]',?,?,?,'inactive','legacy',4,4)",[job.tenant_id,server.id,server.host,server.port,name,a,encryptProvisioningSecret(randomBytes(32).toString('base64url')),r,encryptProvisioningSecret(randomBytes(32).toString('base64url'))]);await central.query('UPDATE tenant_environments SET tenant_database_id=? WHERE id=?',[insert.insertId,job.environment_id]);const [newRows]:any=await central.query('SELECT * FROM tenant_databases WHERE id=?',[insert.insertId]);d=newRows[0];}await central.commit();}catch(e){await central.rollback();throw e;}
 if(server.tls_ca_reference)throw new ProvisioningFailure('CUSTOM_CA_NOT_SUPPORTED_YET');const options={host:server.host,port:server.port,connectTimeout:10000,...(server.tls_required?{ssl:{rejectUnauthorized:true}}:{})};admin=await mysql.createConnection({...options,user:server.provisioning_username,password:decryptProvisioningSecret(server.provisioning_password_encrypted)});const [version]:any=await admin.query({sql:'SELECT VERSION() version',timeout:10000});if(!/^8\./.test(version[0].version)||/mariadb/i.test(version[0].version))throw new ProvisioningFailure('MYSQL_8_REQUIRED');if(!/^rl_tenant_[0-9]+_[a-f0-9]{16}$/.test(d.db_name))throw new ProvisioningFailure('INVALID_DATABASE_NAME');
 await step('database_create',async()=>{await admin!.query({sql:`CREATE DATABASE \`${d.db_name}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,timeout:10000});});await admin.changeUser({database:d.db_name});
 const [pinned]:any=await central.query("SELECT resource_reference FROM environment_provisioning_steps WHERE job_id=? AND step_code='database_template' AND status='success'",[job.id]);if(pinned[0]&&pinned[0].resource_reference!==digest)throw new ProvisioningFailure('TEMPLATE_VERSION_CHANGED');
 await step('database_template',async()=>{const [tables]:any=await admin!.query('SELECT COUNT(*) count FROM information_schema.TABLES WHERE TABLE_SCHEMA=?',[d.db_name]);if(tables[0].count!==0)throw new ProvisioningFailure('PARTIAL_SCHEMA_REQUIRES_REVIEW');await central.query("UPDATE environment_provisioning_steps SET resource_reference=? WHERE job_id=? AND step_code='database_template'",[digest,job.id]);await central.query("INSERT INTO schema_versions (tenant_id,version,status) VALUES (?,?,'running')",[job.tenant_id,VERSION]);for(const sql of splitTenantTemplate(template))await admin!.query({sql,timeout:30000});await central.query("UPDATE schema_versions SET status='success',applied_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND version=? AND status='running'",[job.tenant_id,VERSION]);await central.query('UPDATE tenant_databases SET schema_version=? WHERE id=?',[VERSION,d.id]);});
 const appPass=decryptProvisioningSecret(d.app_password_encrypted),radiusPass=decryptProvisioningSecret(d.radius_password_encrypted),appAccount=mysql.escape(d.db_username)+'@'+mysql.escape(clientHost),radiusAccount=mysql.escape(d.radius_username)+'@'+mysql.escape(clientHost);
 await step('database_users',async()=>{for(const [account,password] of [[appAccount,appPass],[radiusAccount,radiusPass]]){await admin!.query({sql:`CREATE USER ${account} IDENTIFIED BY ${mysql.escape(password)} WITH MAX_USER_CONNECTIONS 4`,timeout:10000});}await admin!.query({sql:`GRANT SELECT,INSERT,UPDATE,DELETE ON \`${d.db_name}\`.* TO ${appAccount}`,timeout:10000});for(const table of ['radcheck','radreply','radusergroup','radgroupcheck','radgroupreply','nas','nasreload'])await admin!.query({sql:`GRANT SELECT ON \`${d.db_name}\`.\`${table}\` TO ${radiusAccount}`,timeout:10000});for(const table of ['radacct','radpostauth'])await admin!.query({sql:`GRANT SELECT,INSERT,UPDATE,DELETE ON \`${d.db_name}\`.\`${table}\` TO ${radiusAccount}`,timeout:10000});});
 await step('database_verify',async()=>{app=await mysql.createConnection({...options,user:d.db_username,password:appPass,database:d.db_name});radius=await mysql.createConnection({...options,user:d.radius_username,password:radiusPass,database:d.db_name});const [result]:any=await app.query({sql:'SELECT DATABASE() name',timeout:10000});if(result[0].name!==d.db_name)throw new ProvisioningFailure('DATABASE_SCOPE_MISMATCH');await app.query({sql:'SELECT id FROM managers LIMIT 1',timeout:10000});await radius.query({sql:'SELECT id FROM nas LIMIT 1',timeout:10000});await radius.query({sql:'SELECT radacctid FROM radacct LIMIT 1',timeout:10000});await central.query("UPDATE tenant_databases SET credentials_state='ready',status='active' WHERE id=?",[d.id]);await central.query("INSERT INTO tenant_environment_status (environment_id,last_seen_at,reported_at,database_status,radius_status) VALUES (?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'healthy','unknown') ON DUPLICATE KEY UPDATE last_seen_at=CURRENT_TIMESTAMP,reported_at=CURRENT_TIMESTAMP,database_status='healthy'",[job.environment_id]);});
 // Database success is not full environment activation: preserve pending subscription and license.
 throw new ProvisioningFailure('ENVIRONMENT_BOOTSTRAP_PENDING');
 }catch(e){const code=e instanceof ProvisioningFailure?e.code:(e as any)?.code||'PROVISIONING_FAILED';if(job){await central.query("UPDATE environment_provisioning_jobs SET status='failed',current_step=?,error_code=?,error_message=?,finished_at=CURRENT_TIMESTAMP WHERE id=?",[currentStep,code,'راجع مرحلة التجهيز ورمز الخطأ؛ لم تبدأ مدة الاشتراك.',job.id]);await central.query("UPDATE tenant_environments SET status='failed' WHERE id=?",[job.environment_id]);if(code!=='ENVIRONMENT_BOOTSTRAP_PENDING')await central.query("UPDATE environment_provisioning_steps SET status='failed',error_code=?,finished_at=CURRENT_TIMESTAMP WHERE job_id=? AND step_code=? AND status='running'",[code,job.id,currentStep]);if(currentStep==='database_verify'&&code!=='ENVIRONMENT_BOOTSTRAP_PENDING')await central.query("INSERT INTO tenant_environment_status (environment_id,reported_at,database_status,radius_status) VALUES (?,CURRENT_TIMESTAMP,'unavailable','unknown') ON DUPLICATE KEY UPDATE reported_at=CURRENT_TIMESTAMP,database_status='unavailable'",[job.environment_id]);await central.query("UPDATE schema_versions SET status='failed',error_message=? WHERE tenant_id=? AND status='running'",[code,job.tenant_id]);await audit(code);}console.error('Provisioning stopped:',code);
 }finally{await Promise.allSettled([admin?.end(),app?.end(),radius?.end()]);if(locked)await central.query('SELECT RELEASE_LOCK(?)',[lockName]);central.release();}}
let stopping=false,running=false;
async function tick(){if(stopping||running)return;running=true;try{await main();}catch{console.error('Database worker could not poll jobs.');}finally{running=false;if(stopping)await db.pool.end();}}
const timer=setInterval(()=>void tick(),5000);
for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>{stopping=true;clearInterval(timer);if(!running)void db.pool.end();});
void tick();
