"use client";
import { useEffect,useMemo,useState } from "react";
import { CheckCircle2,Copy,MessageCircle,ReceiptText } from "lucide-react";
import { useSearchParams } from "next/navigation";
export default function CustomerPaymentPage(){
 const q=useSearchParams(),code=q.get("order")||"",[order,setOrder]=useState<any>(null),[settings,setSettings]=useState<any>(null),[error,setError]=useState(""),[copied,setCopied]=useState(false);
 useEffect(()=>{if(!code){setError("كود طلب الدفع غير موجود.");return}Promise.all([fetch("/api/billing/orders/"+encodeURIComponent(code),{credentials:"include"}),fetch("/api/billing/settings/public",{credentials:"include"})]).then(async([a,b])=>{const x=await a.json(),y=await b.json();if(!a.ok)throw new Error(x.message);if(!b.ok)throw new Error(y.message);setOrder(x.paymentOrder);setSettings(y.settings)}).catch(e=>setError(e.message||"تعذر تحميل بيانات الدفع."))},[code]);
 const message=useMemo(()=>{if(!order||!settings)return"";let t=settings.whatsapp_message_template||"مرحبًا، أرغب بإتمام اشتراكي في Radius Lord. كود الدفع: {{payment_code}}";t=t.replaceAll("{{payment_code}}",order.paymentCode);return t+"\nالخطة: "+order.planName+"\nالاستضافة: "+(order.deploymentName||"-")+"\nالإجمالي: "+order.totalAmount+" "+order.currency},[order,settings]);
 const whatsapp=async()=>{if(!order||!settings?.whatsapp_number)return;try{await fetch("/api/billing/orders/"+encodeURIComponent(order.paymentCode)+"/whatsapp",{method:"POST",credentials:"include"});}finally{window.open("https://wa.me/"+settings.whatsapp_number.replace(/\D/g,"")+"?text="+encodeURIComponent(message),"_blank","noopener,noreferrer")}};
 if(error)return <div className="m-5 rounded-3xl border border-red-200 bg-red-50 p-8 text-center text-sm text-red-600 dark:border-red-500/20 dark:bg-red-500/10">{error}</div>;
 if(!order||!settings)return <div className="p-10 text-center text-sm text-slate-500">جارٍ تجهيز صفحة الدفع...</div>;
 return <div dir="rtl" className="mx-auto max-w-4xl p-4 sm:p-6"><header className="mb-5 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#0758e9] text-white"><ReceiptText className="h-6 w-6"/></span><h1 className="mt-3 text-2xl font-bold text-[#102a63] dark:text-white">الدفع والتفعيل</h1><p className="mt-1 text-xs text-slate-500">احتفظ بكود الدفع، فهو المرجع الخاص بهذه العملية.</p></header>
 <section className="rounded-[26px] border border-[#b9cee3] bg-white/90 p-5 shadow-[0_16px_42px_rgba(39,69,103,.10)] dark:border-white/10 dark:bg-white/[.04]">
  <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#f2f7fd] p-4 dark:bg-white/[.05]"><div><div className="text-[10px] text-slate-400">كود الدفع</div><div dir="ltr" className="mt-1 font-mono text-lg font-extrabold text-[#0758e9]">{order.paymentCode}</div></div><button onClick={()=>{navigator.clipboard.writeText(order.paymentCode);setCopied(true);setTimeout(()=>setCopied(false),1200)}} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#c9dbea] px-3 text-xs font-bold"><Copy className="h-4 w-4"/>{copied?"تم النسخ":"نسخ الكود"}</button></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2"><Info l="الخطة" v={order.planName}/><Info l="المدة" v={order.durationMonths+" شهر"}/><Info l="الاستضافة" v={order.deploymentName||"-"}/><Info l="نوع العملية" v={order.purpose==="renewal"?"تجديد":"اشتراك جديد"}/></div>
  {order.addons?.length>0&&<div className="mt-4 rounded-2xl border border-emerald-200/70 bg-emerald-50/60 p-4 dark:border-emerald-500/20 dark:bg-emerald-500/10"><div className="text-xs font-bold text-emerald-700 dark:text-emerald-300">القيم المضافة</div>{order.addons.map((a:any)=><div key={a.id} className="mt-2 flex justify-between text-xs"><span>{a.nameAr}</span><b>+{a.price} {order.currency}</b></div>)}</div>}
  <div className="mt-5 flex items-end justify-between gap-3 border-t border-slate-200 pt-4 dark:border-white/10"><div><div className="text-xs text-slate-400">الإجمالي المطلوب</div><div className="mt-1 text-2xl font-extrabold text-[#0758e9]">{order.totalAmount} {order.currency}</div></div><span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-3 py-1.5 text-[10px] font-bold text-amber-600 dark:bg-amber-500/10 dark:text-amber-300">بانتظار تأكيد الدفع</span></div>
  {settings.payment_instructions&&<div className="mt-5 rounded-2xl border border-slate-200 p-4 text-xs leading-6 text-slate-600 dark:border-white/10 dark:text-slate-300">{settings.payment_instructions}</div>}
  {settings.whatsapp_enabled&&settings.whatsapp_number?<button onClick={whatsapp} className="mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-emerald-600 text-sm font-bold text-white shadow-[0_10px_25px_rgba(5,150,105,.22)] transition hover:bg-emerald-700"><MessageCircle className="h-5 w-5"/>{settings.whatsapp_button_text||"التواصل عبر واتساب لإتمام الدفع"}</button>:<div className="mt-5 rounded-2xl bg-slate-100 p-4 text-center text-xs text-slate-500 dark:bg-white/5">التواصل عبر WhatsApp غير متاح حاليًا. يرجى التواصل مع الإدارة.</div>}
  <div className="mt-4 flex items-center justify-center gap-2 text-[10px] text-slate-400"><CheckCircle2 className="h-4 w-4 text-emerald-500"/>لن يتم إنشاء الرخصة قبل تأكيد عملية الدفع والتفعيل.</div>
 </section></div>
}
function Info({l,v}:{l:string;v:string}){return <div className="rounded-2xl border border-slate-200/80 p-3 dark:border-white/10"><div className="text-[10px] text-slate-400">{l}</div><div className="mt-1 text-sm font-bold">{v}</div></div>}
