"use client";
import { useEffect,useMemo,useState } from "react";
import { useSearchParams } from "next/navigation";
import { CheckCircle2,CircleDollarSign,RefreshCw } from "lucide-react";
import { CollectionState,CollectionTable,CollectionTableBody,CollectionTableHead } from "@/components/ui/collection-display";
type Order={id:number;paymentCode:string;purpose:string;planName:string;deploymentName:string|null;totalAmount:number;currency:string;status:string;requestedAt:string;paidAt:string|null;customerName:string;customerEmail:string};
const status:any={pending:["جديد","bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:text-blue-300"],awaiting_confirmation:["بانتظار التأكيد","bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-300"],paid:["مدفوع","bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300"],completed:["مكتمل","bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300"],cancelled:["ملغي","bg-red-50 text-red-500 dark:bg-red-500/10 dark:text-red-300"],expired:["منتهي","bg-slate-100 text-slate-500 dark:bg-white/5 dark:text-slate-300"]};
export default function PaymentsPage(){const searchParams=useSearchParams();const selectedCode=searchParams.get("code");const [orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[msg,setMsg]=useState("");
 const load=()=>{setLoading(true);fetch("/api/billing/admin/orders",{credentials:"include",cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.message);setOrders(j.paymentOrders??[])}).catch(e=>setMsg(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);
 const totals=useMemo(()=>({all:orders.length,new:orders.filter(x=>x.purpose==="initial_subscription").length,renewal:orders.filter(x=>x.purpose==="renewal").length,waiting:orders.filter(x=>["pending","awaiting_confirmation"].includes(x.status)).length}),[orders]);
 const confirm=async(o:Order)=>{if(busy)return;setBusy(o.paymentCode);setMsg("");try{const r=await fetch("/api/billing/admin/orders/"+encodeURIComponent(o.paymentCode)+"/confirm",{method:"POST",credentials:"include"}),j=await r.json();if(!r.ok)throw new Error(j.message);setOrders(xs=>xs.map(x=>x.id===o.id?{...x,status:"paid",paidAt:new Date().toISOString()}:x));setMsg("تم تأكيد استلام الدفعة "+o.paymentCode);}catch(e:any){setMsg(e.message||"تعذر تأكيد الدفعة.")}finally{setBusy(null)}};
 return <div dir="rtl" className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold text-[#102a63] dark:text-white">عمليات الدفع</h1><p className="mt-1 text-sm text-slate-500">سجل عمليات الاشتراك والتجديد ومراجعة الدفعات المحلية.</p></div><button onClick={load} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold dark:border-white/10 dark:bg-white/5"><RefreshCw className="h-4 w-4"/>تحديث</button></div>
 <div className="grid gap-3 sm:grid-cols-4"><Stat l="جميع العمليات" v={totals.all}/><Stat l="اشتراكات جديدة" v={totals.new}/><Stat l="تجديدات" v={totals.renewal}/><Stat l="بانتظار التأكيد" v={totals.waiting}/></div>
 {msg&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-xs dark:border-white/10 dark:bg-white/5">{msg}</div>}
 {loading?<CollectionState>جارٍ تحميل عمليات الدفع...</CollectionState>:orders.length===0?<CollectionState>لا توجد عمليات دفع حتى الآن.</CollectionState>:<CollectionTable><CollectionTableHead><tr><th className="p-3">كود الدفع</th><th>العميل</th><th>العملية</th><th>الخطة</th><th>الإجمالي</th><th>الحالة</th><th>التاريخ</th><th className="p-3 text-center">إجراء</th></tr></CollectionTableHead><CollectionTableBody>{orders.map(o=><tr key={o.id} className={`border-t border-slate-100 transition dark:border-white/[.06] ${selectedCode===o.paymentCode?"bg-blue-50/80 ring-1 ring-inset ring-[#0758e9]/20 dark:bg-blue-500/10":""}`}><td className="p-3 font-mono text-xs font-bold text-[#0758e9]" dir="ltr">{o.paymentCode}</td><td><b className="block text-xs">{o.customerName}</b><span className="text-[10px] text-slate-400">{o.customerEmail}</span></td><td><span className="text-xs font-semibold">{o.purpose==="renewal"?"تجديد":"اشتراك جديد"}</span></td><td><b className="block text-xs">{o.planName}</b><span className="text-[10px] text-slate-400">{o.deploymentName||"—"}</span></td><td className="font-bold">{o.totalAmount} {o.currency}</td><td><Badge s={o.status}/></td><td className="text-xs">{new Intl.DateTimeFormat("ar",{dateStyle:"medium"}).format(new Date(o.requestedAt))}</td><td className="p-3 text-center">{["pending","awaiting_confirmation"].includes(o.status)?<button disabled={busy===o.paymentCode} onClick={()=>confirm(o)} className="inline-flex h-9 items-center gap-1.5 rounded-xl bg-emerald-600 px-3 text-[10px] font-bold text-white disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>{busy===o.paymentCode?"جارٍ التأكيد...":"تأكيد الدفع"}</button>:<span className="text-[10px] text-slate-400">—</span>}</td></tr>)}</CollectionTableBody></CollectionTable>}</div>}
function Stat({l,v}:{l:string;v:number}){return <div className="rounded-[20px] border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-white/[.04]"><CircleDollarSign className="h-5 w-5 text-[#0758e9]"/><div className="mt-3 text-2xl font-extrabold">{v}</div><div className="mt-1 text-[10px] text-slate-400">{l}</div></div>}
function Badge({s}:{s:string}){const x=status[s]||[s,"bg-slate-100 text-slate-500"];return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${x[1]}`}>{x[0]}</span>}
