"use client";
import { useEffect,useState } from "react";
import { Activity,ArrowLeft,ArrowRight,Check,CreditCard,Layers3,Pencil,Server,Star,Users,Wifi,X } from "lucide-react";
import { useParams,useRouter,useSearchParams } from "next/navigation";
import ProjectTooltip from "@/components/ui/project-tooltip";
import ProjectDropdown from "@/components/ui/project-dropdown";
import { CURRENCY_OPTIONS } from "@/lib/currencies";

type RecentActivity={id:number;actionCode:string;actionName:string;description:string|null;adminName:string|null;adminUsername:string|null;createdAt:string;metadata:any};
const activityTone:Record<string,string>={CREATE:"bg-emerald-100 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300",UPDATE:"bg-blue-100 text-blue-700 dark:bg-blue-500/15 dark:text-blue-300",DELETE:"bg-red-100 text-red-700 dark:bg-red-500/15 dark:text-red-300"};
type Plan={id:number;name:string;durationMonths:number;maxTenants:number;maxSubscribers:number;maxNas:number;price:number;currency:string;description:string|null;isFeatured:boolean;status:"active"|"inactive"|"disabled";createdAt:string;updatedAt:string};
const STATUS=[{value:"active",label:"نشطة"},{value:"inactive",label:"غير نشطة"},{value:"disabled",label:"معطلة"}];

export default function PlanDetailsPage(){
 const params=useParams(),router=useRouter(),searchParams=useSearchParams();const [plan,setPlan]=useState<Plan|null>(null),[recentActivity,setRecentActivity]=useState<RecentActivity[]>([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[form,setForm]=useState<any>({});
 useEffect(()=>{fetch(`/api/admin/payment-plans/${params.id}`,{credentials:"include",cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{setPlan(d.plan);setForm({...d.plan,description:d.plan.description??""})}).catch(()=>setError("تعذر العثور على الخطة.")).finally(()=>setLoading(false))},[params.id]);
 const loadRecentActivity=()=>fetch(`/api/admin/audit-logs/payment-plan/${params.id}`,{credentials:"include",cache:"no-store"}).then(async r=>r.ok?r.json():null).then(d=>setRecentActivity(d?.logs??[])).catch(()=>setRecentActivity([]));
 useEffect(()=>{loadRecentActivity()},[params.id]);
 useEffect(()=>{if(plan&&searchParams.get("edit")==="1")begin()},[plan?.id,searchParams]);
 const begin=()=>{if(plan){setForm({...plan,description:plan.description??""});setError("");setMessage("");setEditing(true)}};
 const cancel=()=>{setEditing(false);setError("")};const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
 async function save(){setSaving(true);setError("");setMessage("");try{const r=await fetch(`/api/admin/payment-plans/${params.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.message??"تعذر حفظ التعديلات.");setPlan(d.plan);setForm({...d.plan,description:d.plan.description??""});setEditing(false);setMessage(d.message??"تم حفظ التعديلات بنجاح.");loadRecentActivity()}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ التعديلات.")}finally{setSaving(false)}}
 if(loading)return <State>جارٍ تحميل بيانات الخطة...</State>;if(!plan)return <State>{error||"تعذر العثور على الخطة."}</State>;
 return <div className="space-y-3 sm:space-y-4" dir="rtl">
  <section className="rl-surface rounded-[22px] bg-white p-4 shadow-[0_8px_22px_rgba(58,84,112,.08)] dark:bg-[#0d243b]">
   <div className="flex flex-col gap-4 sm:flex-row sm:items-center"><ProjectTooltip label="رجوع إلى الخطط"><button onClick={()=>router.push("/Dashboard/plans")} aria-label="الرجوع إلى الخطط" className="grid h-11 w-11 shrink-0 place-items-center rounded-[14px] border-2 border-[#78afe9] bg-[#e9f2ff] text-[#0758e9]"><ArrowRight className="h-4 w-4"/></button></ProjectTooltip><div className="grid h-12 w-12 shrink-0 place-items-center rounded-[17px] bg-[#e9f2ff] text-[#0758e9] dark:bg-white/[.06]"><CreditCard className="h-6 w-6"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold text-[#17386d] dark:text-[#e3dee6] sm:text-xl">{plan.name}</h2>{plan.isFeatured&&<Star className="h-4 w-4 fill-amber-400 text-amber-400"/>}<Status value={plan.status}/></div><p className="mt-1 text-xs text-slate-500">رقم الخطة #{plan.id}</p></div>{!editing&&<button onClick={begin} className="flex h-11 items-center gap-2 rounded-[14px] border-2 border-[#78afe9] bg-[#e9f2ff] px-3.5 text-xs font-medium text-[#0758e9]"><Pencil className="h-4 w-4"/>تعديل الخطة</button>}</div>
   {(message||error)&&<div className={`mt-3 rounded-[13px] border px-3 py-2 text-xs ${error?"border-red-200 bg-red-50 text-red-600":"border-emerald-200 bg-emerald-50 text-emerald-600"}`}>{error||message}</div>}
  </section>
  <section className="grid gap-3 lg:grid-cols-2">
   <div className="rl-surface rounded-[22px] bg-white p-4 dark:bg-[#0d243b]"><h3 className="mb-4 text-sm font-semibold text-[#17386d] dark:text-[#d8d2dc]">بيانات الخطة</h3>{editing?<div className="ui-state-enter"><div className="grid gap-2 sm:grid-cols-2"><Field label="اسم الخطة" value={form.name} onChange={v=>set("name",v)}/><NumberField label="السعر" value={form.price} onChange={v=>set("price",v)} step=".01"/><NumberField label="المدة بالأشهر" value={form.durationMonths} onChange={v=>set("durationMonths",v)} min={1}/><NumberField label="عدد الشبكات" value={form.maxTenants} onChange={v=>set("maxTenants",v)}/><NumberField label="إجمالي المشتركين" value={form.maxSubscribers} onChange={v=>set("maxSubscribers",v)}/><NumberField label="إجمالي NAS" value={form.maxNas} onChange={v=>set("maxNas",v)}/><label className="text-[11px] text-slate-400">العملة<ProjectDropdown className="mt-1.5" value={form.currency} onChange={v=>set("currency",v)} options={CURRENCY_OPTIONS}/></label><label className="text-[11px] text-slate-400">الحالة<ProjectDropdown className="mt-1.5" value={form.status} onChange={v=>set("status",v)} options={STATUS}/></label><label className="sm:col-span-2"><span className="mb-1.5 block text-[11px] text-slate-400">الوصف</span><textarea value={form.description} onChange={e=>set("description",e.target.value)} className="allow-text-selection min-h-20 w-full rl-surface-soft rounded-[14px] bg-[#f9fbfe] p-3 text-sm outline-none dark:bg-[#38363c]"/></label><label className="sm:col-span-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={form.isFeatured} onChange={e=>set("isFeatured",e.target.checked)}/>خطة مميزة</label></div><div className="mt-3 flex flex-wrap gap-2"><button disabled={saving} onClick={save} className="flex h-10 items-center gap-2 rounded-[13px] bg-[#0758e9] px-4 text-xs font-medium text-white"><Check className="h-4 w-4"/>{saving?"جارٍ الحفظ...":"حفظ التعديلات"}</button><button disabled={saving} onClick={cancel} className="flex h-10 items-center gap-2 rounded-[13px] border border-[#d7e3ef] bg-white px-4 text-xs text-slate-500 dark:bg-[#38363c]"><X className="h-4 w-4"/>إلغاء</button></div></div>:<div className="ui-state-enter grid gap-2 sm:grid-cols-2"><Info icon={CreditCard} label="السعر" value={`${plan.price} ${plan.currency}`}/><Info icon={Layers3} label="المدة" value={`${plan.durationMonths} شهر`}/><Info icon={Wifi} label="عدد الشبكات" value={limit(plan.maxTenants)}/><Info icon={Users} label="إجمالي المشتركين" value={limit(plan.maxSubscribers)}/><Info icon={Server} label="إجمالي NAS" value={limit(plan.maxNas)}/></div>}</div>
   <div className="rl-surface rounded-[22px] bg-white p-4 dark:bg-[#0d243b]"><h3 className="mb-4 text-sm font-semibold text-[#17386d] dark:text-[#d8d2dc]">وصف الخطة</h3><div className="rl-surface-soft min-h-28 rounded-[16px] bg-[#f9fbfe] p-3 text-sm text-slate-600 dark:bg-white/[.035] dark:text-slate-300">{plan.description||"لا يوجد وصف لهذه الخطة."}</div><div className="mt-3 text-[11px] text-slate-400">القيمة 0 للمشتركين وNAS تعني غير محدود.</div></div>
  </section>
  <section className="rl-surface rounded-[22px] bg-white p-4 dark:bg-[#0d243b]">
   <div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 text-sm font-semibold text-[#17386d] dark:text-[#d8d2dc]"><Activity className="h-4 w-4 text-[#0758e9]"/>آخر النشاطات</h3><p className="mt-1 text-[11px] text-slate-400">آخر العمليات الإدارية على هذه الخطة</p></div><button type="button" onClick={()=>router.push(`/Dashboard/logs/admin?entityType=PAYMENT_PLAN&entityId=${plan.id}`)} className="flex h-9 items-center gap-1.5 rounded-[12px] border border-[#9db8d1] bg-[#f7faff] px-3 text-[11px] font-medium text-[#0758e9] transition hover:bg-[#e9f2ff] dark:border-white/[.12] dark:bg-white/[.04] dark:text-[#8fc0ff]">عرض السجل الكامل<ArrowLeft className="h-3.5 w-3.5"/></button></div>
   {recentActivity.length===0?<div className="rl-surface-soft rounded-[16px] bg-[#f9fbfe] p-5 text-center text-xs text-slate-400 dark:bg-white/[.035]">لا توجد نشاطات مسجلة لهذه الخطة حتى الآن.</div>:<div className="space-y-2">{recentActivity.map(item=><div key={item.id} className="rl-surface-soft ui-state-enter flex flex-col gap-2 rounded-[16px] bg-[#f9fbfe] p-3 dark:bg-white/[.035] sm:flex-row sm:items-center"><span className={`inline-flex w-fit shrink-0 rounded-full px-2.5 py-1 text-[10px] font-medium ${activityTone[item.actionCode]??"bg-slate-100 text-slate-600 dark:bg-white/[.08] dark:text-slate-300"}`}>{item.actionName}</span><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium text-slate-650 dark:text-slate-200">{item.description||"عملية إدارية"}</div><div className="mt-1 text-[10px] text-slate-400">بواسطة {item.adminName||item.adminUsername||"النظام"}</div></div><div className="shrink-0 text-[10px] text-slate-400">{formatDateTime(item.createdAt)}</div></div>)}</div>}
  </section>
 </div>
}
function Field({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void}){return <label><span className="mb-1.5 block text-[11px] text-slate-400">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="allow-text-selection h-11 w-full rl-surface-soft rounded-[14px] bg-[#f9fbfe] px-3 text-sm outline-none focus:border-[#6aaeff] focus:ring-4 focus:ring-[#1480ff]/10 dark:bg-[#38363c]"/></label>}
function NumberField({label,value,onChange,min=0,step="1"}:{label:string;value:number;onChange:(v:number)=>void;min?:number;step?:string}){return <label><span className="mb-1.5 block text-[11px] text-slate-400">{label}</span><input type="number" min={min} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} className="allow-text-selection h-11 w-full rl-surface-soft rounded-[14px] bg-[#f9fbfe] px-3 text-sm outline-none focus:border-[#6aaeff] focus:ring-4 focus:ring-[#1480ff]/10 dark:bg-[#38363c]"/></label>}
function Info({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rl-surface-soft rounded-[16px] bg-[#f9fbfe] p-3 dark:bg-white/[.035]"><div className="flex items-center gap-2 text-[11px] text-slate-400"><Icon className="h-4 w-4 text-[#5f91d8]"/>{label}</div><div className="mt-2 text-sm font-medium text-slate-700 dark:text-[#d4ced7]">{value}</div></div>}
function Status({value}:{value:Plan["status"]}){return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${value==="active"?"bg-emerald-50 text-emerald-600":value==="inactive"?"bg-amber-50 text-amber-600":"bg-red-50 text-red-500"}`}>{value==="active"?"نشطة":value==="inactive"?"غير نشطة":"معطلة"}</span>}
function State({children}:{children:React.ReactNode}){return <div className="rl-surface rounded-[22px] bg-white p-8 text-center text-sm text-slate-500 dark:bg-[#0d243b]">{children}</div>}
function limit(v:number){return v===0?"غير محدود":new Intl.NumberFormat("ar").format(v)}

function formatDateTime(value:string|null){if(!value)return "—";return new Intl.DateTimeFormat("ar",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
