"use client";
import {useEffect,useState} from "react";
import {Activity,ArrowRight,Database,Edit3,Plus,Radio,Save,ShieldCheck} from "lucide-react";
import {useAuth} from "@/components/auth/auth-provider";
import ProjectInput from "@/components/ui/project-input";
import ProjectButton from "@/components/ui/project-button";
import ProjectDropdown from "@/components/ui/project-dropdown";
import {CollectionCard,CollectionToolbar,CollectionState} from "@/components/ui/collection-display";
type Health={checkedAt:string;service:string;authentication:string;accounting:string;database:string;overall:string;sessionId:string|null};
type Server={id:number;name:string;host:string;authPort:number;accountingPort:number;testUsername:string;tenantDatabaseId:number|null;probeDatabaseHost?:string;probeDatabaseName?:string;probeDatabaseUsername?:string;probeDatabasePort?:number;probeDatabaseTls?:boolean;discovery?:{status:string;version:string;serviceState:string;checkedAt:string};hasSecret:boolean;hasTestPassword:boolean;lastHealth:Health|null};
const initial={name:"",host:"",authPort:"1812",accountingPort:"1813",secret:"",testUsername:"",testPassword:"",tenantDatabaseId:"",probeDatabaseHost:"",probeDatabaseName:"",probeDatabaseUsername:"",probeDatabasePort:"3306",probeDatabasePassword:"",probeDatabaseTls:false};
const endpoint="/api/admin/platform-settings/radius-servers";
const labels:Record<string,string>={responding:"يستجيب برد موثّق",unavailable:"تعذر التحقق",not_checked:"لم يُفحص",accepted:"نجحت المصادقة",rejected:"رُفض حساب الاختبار",challenge:"يتطلب مصادقة إضافية",acknowledged:"استلم رد المحاسبة",verified:"تم التحقق من سجل الاختبار",record_missing:"سجل الاختبار غير موجود في القاعدة المختارة",connected:"اتصال القاعدة ناجح",healthy:"اجتاز الفحوص",degraded:"الفحص غير مكتمل"};
export default function RadiusServersPage(){
 const {isMasterAdmin,loading}=useAuth();
 const [rows,setRows]=useState<Server[]>([]),[databases,setDatabases]=useState<{id:number;name:string}[]>([]),[pending,setPending]=useState(true),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[editing,setEditing]=useState<number|null>(null),[open,setOpen]=useState(false),[form,setForm]=useState(initial),[expanded,setExpanded]=useState<number|null>(null);
 async function load(){setPending(true);try{const r=await fetch(endpoint,{credentials:"include"}),j=await r.json();if(!r.ok)throw new Error(j.message);setRows(j.servers);setDatabases(j.databases);}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل الخوادم.");}finally{setPending(false);}}
 useEffect(()=>{if(isMasterAdmin)void load();},[isMasterAdmin]);
 function change(k:keyof typeof initial,v:string|boolean){setForm(f=>({...f,[k]:v}));setMessage("");}
 function edit(row?:Server){setEditing(row?.id??null);setForm(row?{...initial,name:row.name,host:row.host,authPort:String(row.authPort),accountingPort:String(row.accountingPort),testUsername:row.testUsername,probeDatabaseHost:row.probeDatabaseHost??"",probeDatabaseName:row.probeDatabaseName??"",probeDatabaseUsername:row.probeDatabaseUsername??"",probeDatabasePort:String(row.probeDatabasePort??3306),probeDatabaseTls:row.probeDatabaseTls??false,tenantDatabaseId:row.tenantDatabaseId?String(row.tenantDatabaseId):""}:initial);setOpen(true);setError("");setMessage("");}
 async function save(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError("");setMessage("");try{const r=await fetch(endpoint+(editing?`/${editing}`:""),{method:editing?"PUT":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,probeDatabasePort:Number(form.probeDatabasePort),authPort:Number(form.authPort),accountingPort:Number(form.accountingPort),tenantDatabaseId:form.tenantDatabaseId?Number(form.tenantDatabaseId):null})}),j=await r.json();if(!r.ok)throw new Error(j.message);setOpen(false);setForm(initial);await load();setMessage("تم حفظ المخدم. استخدم فحص الصحة للتحقق الفعلي.");}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ المخدم.");}finally{setBusy(false);}}
 async function inspect(row:Server){if(busy)return;setBusy(true);setExpanded(row.id);setError("");setMessage("");try{const r=await fetch(`${endpoint}/${row.id}/health`,{method:"POST",credentials:"include"}),j=await r.json();if(!r.ok)throw new Error(j.message);setRows(current=>current.map(s=>s.id===row.id?{...s,lastHealth:j.health}:s));}catch(e){setError(e instanceof Error?e.message:"تعذر فحص المخدم.");}finally{setBusy(false);}}
 if(loading)return <CollectionState loading>جارٍ التحميل...</CollectionState>;
 if(!isMasterAdmin)return <CollectionState>هذه الصفحة خاصة بالمدير الرئيسي.</CollectionState>;
 return <div dir="rtl" className="space-y-4 text-slate-800 dark:text-slate-200">
 <CollectionToolbar responsive icon={Radio} title="خوادم FreeRADIUS" description="إعداد الاتصال والتحقق من المصادقة والمحاسبة وقاعدة الاختبار" query={query} onQueryChange={setQuery} searchPlaceholder="بحث عن مخدم..." primaryAction={<ProjectButton disabled={busy} onClick={()=>edit()}><Plus/>إضافة مخدم</ProjectButton>}/>
 {error&&<p role="alert" className="rounded-xl bg-red-500/10 p-3 text-sm text-red-600 dark:text-red-300">{error}</p>}{message&&<p role="status" className="rounded-xl bg-emerald-500/10 p-3 text-sm text-emerald-700 dark:text-emerald-300">{message}</p>}
 {open?<section className="rl-surface rounded-[22px] border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-white/[.035] sm:p-6"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 font-bold"><Radio className="h-5 w-5 text-blue-500"/>{editing?"تعديل مخدم FreeRADIUS":"إضافة مخدم FreeRADIUS"}</h2><ProjectButton variant="back" size="icon" aria-label="العودة إلى الخوادم" disabled={busy} onClick={()=>setOpen(false)}><ArrowRight/></ProjectButton></div><form onSubmit={save} className="space-y-5"><fieldset disabled={busy} className="grid min-w-0 gap-4 sm:grid-cols-2">
 {([{key:"name",label:"اسم المخدم",required:true},{key:"host",label:"عنوان IPv4 أو دومين المخدم",required:true},{key:"authPort",label:"منفذ المصادقة UDP",required:true},{key:"accountingPort",label:"منفذ المحاسبة UDP",required:true},{key:"secret",label:editing?"Shared Secret (فارغ للاحتفاظ به)":"Shared Secret",required:!editing},{key:"testUsername",label:"اسم مستخدم الاختبار",required:false},{key:"testPassword",label:editing?"كلمة مرور الاختبار (فارغة للاحتفاظ بها)":"كلمة مرور الاختبار",required:false}] as const).map(field=><label key={field.key} className="rl-field-label">{field.label}<ProjectInput className="mt-2" required={field.required} type={field.key==="secret"||field.key==="testPassword"?"password":field.key.endsWith("Port")?"number":"text"} min={field.key.endsWith("Port")?1:undefined} max={field.key.endsWith("Port")?65535:undefined} step={1} maxLength={field.key==="host"?253:field.key==="secret"?253:field.key==="testPassword"?128:100} autoComplete={field.key==="secret"||field.key==="testPassword"?"new-password":"off"} dir={field.key==="name"?"rtl":"ltr"} value={form[field.key]} onChange={e=>change(field.key,e.target.value)}/></label>)}
 <div className="min-w-0"><p className="rl-field-label mb-2">قاعدة الزبون للتحقق من سجل المحاسبة</p><ProjectDropdown value={form.tenantDatabaseId} onChange={v=>change("tenantDatabaseId",v)} options={[{value:"",label:"لم تُحدد قاعدة اختبار",hint:"المصادقة والمحاسبة دون إثبات وصول السجل لقاعدة الزبون"},...databases.map(d=>({value:String(d.id),label:d.name}))]}/></div>
 <div className="sm:col-span-2 space-y-4 rounded-[14px] border border-slate-200 p-4 dark:border-white/10"><h3 className="text-sm font-semibold">قاعدة اختبار مستقلة لصحة البنية التحتية</h3><p className="text-xs leading-6 text-slate-500">قاعدة موجودة مسبقًا بجداول FreeRADIUS وحساب الاختبار، ومربوطة بخدمة RADIUS. يبدأ اسمها بـ rl_infrastructure_ ولا تتبع أي زبون. بياناتها مطلوبة للفحص الشامل؛ عند إدخالها تُستخدم بدل قاعدة الزبون في فحص هذا المخدم.</p><div className="grid gap-4 sm:grid-cols-2">{([{key:"probeDatabaseHost",label:"عنوان MySQL للاختبار"},{key:"probeDatabasePort",label:"منفذ MySQL"},{key:"probeDatabaseName",label:"اسم القاعدة مثل rl_infrastructure_radius"},{key:"probeDatabaseUsername",label:"حساب قراءة قاعدة الاختبار"},{key:"probeDatabasePassword",label:"كلمة المرور (فارغة للاحتفاظ بها)"}] as const).map(field=><label key={field.key} className="rl-field-label">{field.label}<ProjectInput className="mt-2" dir="ltr" autoComplete="off" value={form[field.key]} onChange={e=>change(field.key,e.target.value)} type={field.key==="probeDatabasePassword"?"password":field.key==="probeDatabasePort"?"number":"text"}/></label>)}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.probeDatabaseTls} onChange={e=>change("probeDatabaseTls",e.target.checked)}/>اتصال MySQL عبر TLS</label></div>
 </fieldset><p className="text-xs leading-6 text-slate-500 dark:text-slate-400">عرّف عنوان مصدر الباك إند كعميل RADIUS على المخدم بنفس Shared Secret. استخدم حساب اختبار مخصصًا وموجودًا في إعدادات FreeRADIUS. الفحص يرسل طلب مصادقة وسجل محاسبة تجريبيًا من نوع Stop، وقد يظهر في سجلات المخدم والقاعدة؛ لا يضيف حسابًا أو يعدّل إعداد الخدمة. الأسرار تحفظ مشفرة.</p><div className="flex justify-end gap-2"><ProjectButton variant="secondary" disabled={busy} onClick={()=>setOpen(false)}>إلغاء</ProjectButton><ProjectButton type="submit" disabled={busy}><Save/>{busy?"جارٍ الحفظ...":"حفظ المخدم"}</ProjectButton></div></form></section>:pending?<CollectionState loading>جارٍ تحميل مخدمات FreeRADIUS...</CollectionState>:<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rows.filter(row=>`${row.name} ${row.host}`.toLowerCase().includes(query.toLowerCase())).map(row=><CollectionCard key={row.id} onOpen={()=>{if(!busy)setExpanded(expanded===row.id?null:row.id);}}><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-500/10 p-3 text-blue-500"><Radio className="h-6 w-6"/></span><div className="min-w-0"><h2 className="truncate font-bold">{row.name}</h2><p className="mt-1 break-all text-xs text-slate-500" dir="ltr">{row.host}</p></div></div>{row.discovery&&<p className="mt-3 text-xs text-blue-500">مكتشفة تلقائيًا — {row.discovery.serviceState} — {row.discovery.version}{!row.lastHealth&&" — بانتظار التحقق"}</p>}<div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-500"><span>مصادقة: {row.authPort}</span><span>محاسبة: {row.accountingPort}</span></div><p className="mt-2 text-xs text-slate-500">{row.lastHealth?"نتيجة آخر فحص محفوظة — افتح لعرض التفاصيل":"لم يُفحص المخدم بعد"}</p><div className="mt-4 flex flex-wrap gap-2" onClick={e=>e.stopPropagation()}><ProjectButton variant="secondary" disabled={busy} onClick={()=>void inspect(row)}><Activity className="text-emerald-500"/>{busy&&expanded===row.id?"جارٍ الفحص...":"فحص الصحة"}</ProjectButton><ProjectButton variant="ghost" disabled={busy} onClick={()=>edit(row)}><Edit3/>تعديل</ProjectButton></div>
 {expanded===row.id&&<div className="mt-4 space-y-3 border-t border-slate-200 pt-4 dark:border-white/10">{row.lastHealth?<><p className="text-xs text-slate-500">وقت آخر فحص: {new Date(row.lastHealth.checkedAt).toLocaleString("ar")}</p><dl className="space-y-3">{([{key:"service",label:"استجابة الخدمة",icon:Radio},{key:"authentication",label:"المصادقة",icon:ShieldCheck},{key:"accounting",label:"المحاسبة",icon:Activity},{key:"database",label:"قاعدة الزبون",icon:Database}] as const).map(item=><div key={item.key} className="flex flex-wrap items-center justify-between gap-2 text-xs"><dt className="flex items-center gap-2"><item.icon className="h-4 w-4 text-blue-500"/>{item.label}</dt><dd className={['accepted','verified','responding','connected'].includes(row.lastHealth![item.key])?"text-emerald-600 dark:text-emerald-400":"text-amber-600 dark:text-amber-400"}>{labels[row.lastHealth![item.key]]??row.lastHealth![item.key]}</dd></div>)}</dl><p className="text-xs leading-6 text-slate-500">هذه نتيجة فحص المخدم والقاعدة المختارة في الوقت المبين؛ لا تفعّل بيئات الزبائن ولا تثبت سلامة كل قواعدهم.</p></>:<p className="text-xs text-slate-500">نفّذ فحص الصحة لعرض النتيجة.</p>}</div>}
 </CollectionCard>)}{!rows.length&&<CollectionState>لم تضف مخدمات FreeRADIUS بعد.</CollectionState>}{rows.length>0&&!rows.some(row=>`${row.name} ${row.host}`.toLowerCase().includes(query.toLowerCase()))&&<CollectionState>لا توجد خوادم تطابق البحث.</CollectionState>}</div>}
 </div>;
}
