"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { CreditCard, Plus, Search, Server, Star, Users, Wifi } from "lucide-react";
import { useRouter } from "next/navigation";
import ProjectDropdown from "@/components/ui/project-dropdown";
import { CURRENCY_OPTIONS } from "@/lib/currencies";
import { CollectionDisplayControls, CollectionGridSelectionMark, CollectionSelectionBar, CollectionSelectionBox, useCollectionDisplay } from "@/components/ui/collection-display";

type Plan={id:number;name:string;durationMonths:number;maxTenants:number;maxSubscribers:number;maxNas:number;price:number;currency:string;description:string|null;isFeatured:boolean;status:"active"|"inactive"|"disabled"};
const empty={name:"",durationMonths:1,maxTenants:1,maxSubscribers:0,maxNas:0,price:0,currency:"USD",description:"",isFeatured:false,status:"active" as const};
export default function PlansPage(){
 const router=useRouter();
 const [plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[editing,setEditing]=useState<Plan|null>(null),[form,setForm]=useState<any>(empty),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const {view,setView,selected,setSelected,selectionMode,setSelectionMode,toggle,setAll}=useCollectionDisplay<number>("payment-plans","grid");
 const load=()=>fetch("/api/admin/payment-plans",{credentials:"include",cache:"no-store"}).then(r=>r.json()).then(d=>setPlans(d.plans??[])).finally(()=>setLoading(false));
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>plans.filter(p=>[p.name,p.currency,p.description].some(v=>String(v??"").toLowerCase().includes(query.toLowerCase()))),[plans,query]);
 const open=(p:Plan)=>{setEditing(p);setForm({...p,description:p.description??""});setMessage("")};
 const allSelected=filtered.length>0&&filtered.every(p=>selected.has(p.id));
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");const r=await fetch(editing?`/api/admin/payment-plans/${editing.id}`:"/api/admin/payment-plans",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify(form)});const d=await r.json();setSaving(false);if(!r.ok){setMessage(d.message??"تعذر حفظ الخطة.");return}setEditing(null);setForm({...empty});setMessage("");await load();}
 return <div className="space-y-4" dir="rtl">
  <section className="rl-surface flex flex-col gap-3 rounded-[22px] bg-white p-4 dark:bg-[#0d243b] lg:flex-row lg:items-center lg:justify-between">
   <div><h2 className="flex items-center gap-2 text-lg font-semibold text-slate-800 dark:text-slate-100"><CreditCard className="h-5 w-5 text-[#0758e9]"/>خطط الاشتراكات</h2><p className="mt-1 text-xs text-slate-500">إدارة خطط Radius Lord وحدود الموارد لكل Customer</p></div>
   <div className="flex flex-wrap gap-2"><CollectionDisplayControls view={view} onViewChange={setView} selectionMode={selectionMode} onSelectionModeChange={setSelectionMode} allSelected={allSelected} onToggleAll={()=>setAll(filtered.map(p=>p.id),!allSelected)}/><div className="relative"><Search className="absolute right-3 top-3.5 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث عن خطة..." className="h-11 rounded-[15px] border border-[#d7e3ef] bg-[#f9fbfe] pr-9 pl-3 text-sm outline-none dark:border-white/10 dark:bg-[#38363c]"/></div><button onClick={()=>router.push("/Dashboard/plans/add")} className="flex h-11 items-center gap-2 rounded-[15px] bg-[#0758e9] px-4 text-xs font-semibold text-white"><Plus className="h-4 w-4"/>إضافة خطة</button></div>
  </section>
  <CollectionSelectionBar count={selected.size} noun="الخطط" onClear={()=>setSelected(new Set())}/>
  {loading?<div className="rl-surface rounded-[22px] bg-white p-8 text-center text-sm dark:bg-[#0d243b]">جارٍ تحميل الخطط...</div>:view==="grid"?<section className="ui-state-enter grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(p=><PlanCard key={p.id} p={p} onEdit={()=>open(p)} selectionMode={selectionMode} selected={selected.has(p.id)} onToggle={()=>toggle(p.id)}/>)}</section>:<section className="ui-state-enter overflow-x-auto rl-surface rounded-[22px] bg-white dark:bg-[#0d243b]"><table className="w-full min-w-[850px] text-right text-xs"><thead className="bg-[#d3e2f2] text-[#17386d] dark:bg-[#3b383e] dark:text-slate-200"><tr><th className="w-12 p-3 text-center"><CollectionSelectionBox checked={allSelected} onChange={()=>setAll(filtered.map(p=>p.id),!allSelected)} label="تحديد كل الخطط الظاهرة"/></th><th className="p-3">الخطة</th><th>السعر</th><th>المدة</th><th>الشبكات</th><th>المشتركون</th><th>NAS</th><th>الحالة</th></tr></thead><tbody className="divide-y divide-[#c4d3e2] dark:divide-white/10">{filtered.map(p=><tr key={p.id} onClick={()=>open(p)} className={`cursor-pointer hover:bg-[#e9f2ff] dark:hover:bg-white/[.04] ${selected.has(p.id)?"bg-[#dbe9f7] dark:bg-white/[.06]":""}`}><td className="w-12 p-3 text-center" onClick={e=>e.stopPropagation()}><CollectionSelectionBox checked={selected.has(p.id)} onChange={()=>toggle(p.id)} label={`تحديد ${p.name}`}/></td><td className="p-3 font-semibold">{p.name}{p.isFeatured&&<Star className="mr-2 inline h-3.5 w-3.5 fill-amber-400 text-amber-400"/>}</td><td>{p.price} {p.currency}</td><td>{p.durationMonths} شهر</td><td>{limit(p.maxTenants)}</td><td>{limit(p.maxSubscribers)}</td><td>{limit(p.maxNas)}</td><td><Status value={p.status}/></td></tr>)}</tbody></table></section>}
  {(editing||form.name!==""||message)&&<PlanForm form={form} setForm={setForm} editing={editing} saving={saving} message={message} close={()=>{setEditing(null);setForm({...empty});setMessage("")}} submit={submit}/>}
 </div>
}
function PlanCard({p,onEdit,selectionMode,selected,onToggle}:{p:Plan;onEdit:()=>void;selectionMode:boolean;selected:boolean;onToggle:()=>void}){return <article onClick={()=>selectionMode?onToggle():onEdit()} className={`rl-surface cursor-pointer rounded-[22px] bg-[#e7eef6] p-4 transition hover:-translate-y-1 hover:bg-[#dce9f7] dark:bg-[#243445] dark:hover:bg-[#2b4055] ${selected?"ring-2 ring-[#1479ff]/25 border-[#6aaeff]":""}`}>{selectionMode&&<div className="mb-2 flex justify-end"><CollectionGridSelectionMark checked={selected}/></div>}<div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-base font-semibold">{p.name}{p.isFeatured&&<Star className="h-4 w-4 fill-amber-400 text-amber-400"/>}</div><div className="mt-1 text-xs text-slate-500">{p.durationMonths} شهر</div></div><Status value={p.status}/></div><div className="mt-5 text-2xl font-semibold text-[#0758e9]">{p.price} <span className="text-xs">{p.currency}</span></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric icon={Wifi} label="الشبكات" value={limit(p.maxTenants)}/><Metric icon={Users} label="المشتركون" value={limit(p.maxSubscribers)}/><Metric icon={Server} label="NAS" value={limit(p.maxNas)}/></div>{p.description&&<p className="mt-3 line-clamp-2 text-xs text-slate-500">{p.description}</p>}</article>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rl-surface-soft rounded-[14px] bg-[#d8e3ee] p-2 text-center dark:bg-[#30465b]"><Icon className="mx-auto h-4 w-4 text-[#397bd5]"/><div className="mt-1 text-[10px] text-slate-400">{label}</div><div className="mt-1 text-xs font-semibold">{value}</div></div>}
function Status({value}:{value:Plan["status"]}){const t=value==="active"?"نشطة":value==="inactive"?"غير نشطة":"معطلة";return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${value==="active"?"bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10":value==="inactive"?"bg-amber-50 text-amber-600 dark:bg-amber-500/10":"bg-red-50 text-red-500 dark:bg-red-500/10"}`}>{t}</span>}
function PlanForm({form,setForm,editing,saving,message,close,submit}:any){const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-3 backdrop-blur-[2px]"><form onSubmit={submit} className="ui-state-enter rl-surface w-full max-w-2xl rounded-[22px] bg-white p-5 shadow-2xl dark:bg-[#0d243b]"><div className="flex items-center justify-between"><div><h3 className="font-semibold">{editing?"تعديل خطة الاشتراك":"إضافة خطة اشتراك"}</h3><p className="mt-1 text-xs text-slate-500">القيمة 0 للمشتركين وNAS تعني غير محدود.</p></div><button type="button" onClick={close} className="rounded-xl border px-3 py-2 text-xs">إغلاق</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["name","اسم الخطة","text"],["price","السعر","number"],["durationMonths","المدة بالأشهر","number"],["maxTenants","عدد الشبكات","number"],["maxSubscribers","إجمالي المشتركين","number"],["maxNas","إجمالي NAS","number"]].map(([k,l,t])=><label key={k} className="text-xs text-slate-500">{l}<input required type={t} min={t==="number"?0:undefined} step={k==="price"?"0.01":"1"} value={form[k]} onChange={e=>set(k,t==="number"?Number(e.target.value):e.target.value)} className="mt-1 h-11 w-full rounded-[14px] border border-[#d7e3ef] bg-[#f9fbfe] px-3 text-sm text-slate-700 outline-none dark:border-white/10 dark:bg-[#38363c] dark:text-slate-200"/></label>)}<label className="text-xs text-slate-500">العملة<ProjectDropdown className="mt-1" value={form.currency} onChange={v=>set("currency",v)} options={CURRENCY_OPTIONS}/></label><label className="text-xs text-slate-500">الحالة<ProjectDropdown className="mt-1" value={form.status} onChange={v=>set("status",v)} options={PLAN_STATUS_OPTIONS}/></label><label className="sm:col-span-2 text-xs text-slate-500">الوصف<textarea value={form.description} onChange={e=>set("description",e.target.value)} className="mt-1 min-h-20 w-full rounded-[14px] border border-[#d7e3ef] bg-[#f9fbfe] p-3 dark:border-white/10 dark:bg-[#38363c]"/></label><label className="sm:col-span-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={form.isFeatured} onChange={e=>set("isFeatured",e.target.checked)}/>خطة مميزة</label></div>{message&&<div className="mt-3 text-xs text-red-500">{message}</div>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-[14px] border px-4 py-2.5 text-xs">إلغاء</button><button disabled={saving} className="rounded-[14px] bg-[#0758e9] px-5 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{saving?"جارٍ الحفظ...":editing?"حفظ التعديلات":"إنشاء الخطة"}</button></div></form></div>}
const PLAN_STATUS_OPTIONS=[{value:"active",label:"نشطة"},{value:"inactive",label:"غير نشطة"},{value:"disabled",label:"معطلة"}];
function limit(v:number){return v===0?"غير محدود":new Intl.NumberFormat("ar").format(v)}
