"use client";
import { useEffect, useMemo, useState } from "react";
import { CreditCard, Eye, Pencil, Plus, Server, Star, Trash2, Users, Wifi } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import ConfirmDeleteDialog from "@/components/ui/confirm-delete-dialog";
import { CollectionCard, CollectionGrid, CollectionItemActions, CollectionState, CollectionTable, CollectionTableBody, CollectionTableHead, CollectionToolbar, CollectionStatusFilters, CollectionSelectionBar, CollectionSelectionBox, collectionRowClass, useCollectionDisplay } from "@/components/ui/collection-display";

type DeploymentOption={id:number;deploymentTypeId:number;code:string;nameAr:string;price:number;isDefault:boolean;status:"active"|"inactive"};
type Plan={id:number;name:string;durationMonths:number;maxTenants:number;maxSubscribers:number;maxNas:number;price:number;currency:string;description:string|null;isFeatured:boolean;status:"active"|"inactive"|"disabled";deploymentOptions:DeploymentOption[]};
export default function PlansPage(){
 const router=useRouter();const searchParams=useSearchParams();
 const [plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState<"all"|Plan["status"]>("all");
 const [deleteIds,setDeleteIds]=useState<number[]>([]),[deleting,setDeleting]=useState(false),[notice,setNotice]=useState("");
 const {view,setView,selected,setSelected,selectionMode,setSelectionMode,toggle,setAll}=useCollectionDisplay<number>("payment-plans","grid");
 const load=()=>fetch("/api/admin/payment-plans",{credentials:"include",cache:"no-store"}).then(r=>r.json()).then(d=>setPlans(d.plans??[])).finally(()=>setLoading(false));
 useEffect(()=>{load();if(searchParams.get("created")==="1"){setNotice("تم إنشاء الخطة بنجاح.");router.replace("/Dashboard/plans")}},[]);
 const statusCounts=useMemo(()=>({all:plans.length,active:plans.filter(p=>p.status==="active").length,inactive:plans.filter(p=>p.status==="inactive").length,disabled:plans.filter(p=>p.status==="disabled").length}),[plans]);
 const filtered=useMemo(()=>plans.filter(p=>(statusFilter==="all"||p.status===statusFilter)&&[p.name,p.currency,p.description].some(v=>String(v??"").toLowerCase().includes(query.toLowerCase()))),[plans,query,statusFilter]);
 const open=(p:Plan)=>router.push(`/Dashboard/plans/${p.id}`);
 const edit=(p:Plan)=>router.push(`/Dashboard/plans/${p.id}?edit=1`);
 const allSelected=filtered.length>0&&filtered.every(p=>selected.has(p.id));
 const askDelete=(ids:number[])=>setDeleteIds(ids);const deleteNames=deleteIds.map(id=>plans.find(p=>p.id===id)?.name).filter((x):x is string=>Boolean(x));
 const confirmDelete=async()=>{const ids=[...deleteIds];setDeleting(true);setNotice("");for(const id of ids){const r=await fetch(`/api/admin/payment-plans/${id}`,{method:"DELETE",credentials:"include"});const d=await r.json();if(!r.ok){setDeleting(false);setNotice(d.message??"تعذر حذف الخطة.");return}}setPlans(old=>old.filter(p=>!ids.includes(p.id)));setSelected(new Set());setDeleteIds([]);setDeleting(false);setNotice(ids.length>1?"تم حذف الخطط المحددة بنجاح.":"تم حذف الخطة بنجاح.");};
 return <div className="space-y-4" dir="rtl">
  <CollectionToolbar icon={CreditCard} title="خطط الاشتراكات" description="إدارة خطط Radius Lord وحدود الموارد لكل Customer" view={view} onViewChange={setView} selectionMode={selectionMode} onSelectionModeChange={setSelectionMode} allSelected={allSelected} onToggleAll={()=>setAll(filtered.map(p=>p.id),!allSelected)} query={query} onQueryChange={setQuery} searchPlaceholder="بحث عن خطة..." filters={<CollectionStatusFilters value={statusFilter} onChange={setStatusFilter} items={[{value:"all",label:"الكل",count:statusCounts.all,dot:"bg-[#0758e9]"},{value:"active",label:"نشطة",count:statusCounts.active,dot:"bg-emerald-500"},{value:"inactive",label:"غير نشطة",count:statusCounts.inactive,dot:"bg-amber-500"},{value:"disabled",label:"معطلة",count:statusCounts.disabled,dot:"bg-red-500"}]} />} primaryAction={<button onClick={()=>router.push("/Dashboard/plans/add")} className="flex h-11 items-center gap-2 rounded-[15px] bg-[#0758e9] px-4 text-xs font-semibold text-white"><Plus className="h-4 w-4"/>إضافة خطة</button>} />
  <CollectionSelectionBar count={selected.size} noun="الخطط" onClear={()=>setSelected(new Set())}>{selected.size>0&&<button type="button" onClick={()=>askDelete(Array.from(selected))} className="flex h-9 items-center gap-2 rounded-[12px] bg-red-600 px-3 text-xs font-semibold text-white"><Trash2 className="h-4 w-4"/>حذف المحدد</button>}</CollectionSelectionBar>
  {notice&&<div className={`rounded-[14px] px-4 py-3 text-xs font-semibold ${notice.includes("بنجاح")?"bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300":"bg-red-50 text-red-600 dark:bg-red-500/10 dark:text-red-300"}`}>{notice}</div>}
  {loading?<CollectionState>جارٍ تحميل الخطط...</CollectionState>:view==="grid"?<CollectionGrid>{filtered.map(p=><PlanCard key={p.id} p={p} onOpen={()=>open(p)} onEdit={()=>edit(p)} onDelete={()=>askDelete([p.id])} selectionMode={selectionMode} selected={selected.has(p.id)} onToggle={()=>toggle(p.id)}/>)}</CollectionGrid>:<CollectionTable><CollectionTableHead><tr><th className="w-12 p-3 text-center"><CollectionSelectionBox checked={allSelected} onChange={()=>setAll(filtered.map(p=>p.id),!allSelected)} label="تحديد كل الخطط الظاهرة"/></th><th className="p-3">الخطة</th><th>خيارات الاستضافة</th><th>المدة</th><th>الشبكات</th><th>المشتركون</th><th>NAS</th><th>الحالة</th><th className="w-14 text-center">إجراء</th></tr></CollectionTableHead><CollectionTableBody>{filtered.map(p=><tr key={p.id} onClick={()=>open(p)} className={collectionRowClass(selected.has(p.id))}><td className="w-12 p-3 text-center" onClick={e=>e.stopPropagation()}><CollectionSelectionBox checked={selected.has(p.id)} onChange={()=>toggle(p.id)} label={`تحديد ${p.name}`}/></td><td className="p-3 font-semibold">{p.name}{p.isFeatured&&<Star className="mr-2 inline h-3.5 w-3.5 fill-amber-400 text-amber-400"/>}</td><td><DeploymentPrices p={p}/></td><td>{p.durationMonths} شهر</td><td>{limit(p.maxTenants)}</td><td>{limit(p.maxSubscribers)}</td><td>{limit(p.maxNas)}</td><td><Status value={p.status}/></td><td className="w-14 text-center"><CollectionItemActions items={[{label:"عرض التفاصيل",icon:Eye,tone:"view",onClick:()=>open(p)},{label:"تعديل",icon:Pencil,tone:"edit",onClick:()=>edit(p)},{label:"حذف",icon:Trash2,tone:"danger",danger:true,separatorBefore:true,onClick:()=>askDelete([p.id])}]} /></td></tr>)}</CollectionTableBody></CollectionTable>}

  <ConfirmDeleteDialog open={deleteIds.length>0} title={deleteIds.length>1?"تأكيد حذف الخطط":"تأكيد حذف الخطة"} description={deleteIds.length>1?"راجع أسماء الخطط المحددة قبل تأكيد الحذف.":"راجع اسم الخطة قبل تأكيد الحذف."} items={deleteNames} busy={deleting} onCancel={()=>!deleting&&setDeleteIds([])} onConfirm={confirmDelete}/>
 </div>
}
function PlanCard({p,onOpen,onEdit,onDelete,selectionMode,selected,onToggle}:{p:Plan;onOpen:()=>void;onEdit:()=>void;onDelete:()=>void;selectionMode:boolean;selected:boolean;onToggle:()=>void}){return <CollectionCard selectionMode={selectionMode} selected={selected} onToggle={onToggle} onOpen={onOpen}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2 text-base font-semibold">{p.name}{p.isFeatured&&<Star className="h-4 w-4 fill-amber-400 text-amber-400"/>}</div><div className="mt-1 text-xs text-slate-500">{p.durationMonths} شهر</div></div><div className="flex shrink-0 items-center gap-2"><Status value={p.status}/>{!selectionMode&&<CollectionItemActions items={[{label:"عرض التفاصيل",icon:Eye,tone:"view",onClick:onOpen},{label:"تعديل",icon:Pencil,tone:"edit",onClick:onEdit},{label:"حذف",icon:Trash2,tone:"danger",danger:true,separatorBefore:true,onClick:()=>askDelete([p.id])}]} />}</div></div><div className="mt-4 space-y-1.5">{p.deploymentOptions?.filter(o=>o.status==="active").map(o=><div key={o.id} className="flex items-center justify-between gap-3 rounded-[11px] bg-[#f6f9fd] px-2.5 py-2 text-[11px] dark:bg-white/[.04]"><span className="truncate text-slate-500">{o.nameAr}{o.isDefault&&<span className="mr-1 text-[#0758e9]">• افتراضية</span>}</span><span className="shrink-0 font-semibold text-[#0758e9]">{o.price} {p.currency}</span></div>)}</div><div className="mt-4 grid grid-cols-3 gap-2"><Metric icon={Wifi} label="الشبكات" value={limit(p.maxTenants)}/><Metric icon={Users} label="المشتركون" value={limit(p.maxSubscribers)}/><Metric icon={Server} label="NAS" value={limit(p.maxNas)}/></div>{p.description&&<p className="mt-3 line-clamp-2 text-xs text-slate-500">{p.description}</p>}</CollectionCard>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rl-surface-soft rounded-[14px] bg-[#f9fbfe] p-2 text-center transition-colors duration-300 group-hover:bg-white/70 dark:bg-white/[.035] dark:group-hover:bg-white/[.055]"><Icon className="mx-auto h-4 w-4 text-[#397bd5]"/><div className="mt-1 text-[10px] text-slate-400">{label}</div><div className="mt-1 text-xs font-semibold">{value}</div></div>}
function Status({value}:{value:Plan["status"]}){const t=value==="active"?"نشطة":value==="inactive"?"غير نشطة":"معطلة";return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${value==="active"?"bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10":value==="inactive"?"bg-amber-50 text-amber-600 dark:bg-amber-500/10":"bg-red-50 text-red-500 dark:bg-red-500/10"}`}>{t}</span>}
function limit(v:number){return v===0?"غير محدود":new Intl.NumberFormat("ar").format(v)}

function DeploymentPrices({p}:{p:Plan}){const options=(p.deploymentOptions??[]).filter(o=>o.status==="active");return <div className="space-y-1">{options.map(o=><div key={o.id} className="text-[11px]"><span className="text-slate-500">{o.nameAr}: </span><span className="font-semibold text-[#0758e9]">{o.price} {p.currency}</span></div>)}</div>}
