"use client";
import { useEffect, useState } from "react";
import { Server, Plus, Pencil, Eye, Save } from "lucide-react";
import { useAuth } from "@/components/auth/auth-provider";
import ProjectInput from "@/components/ui/project-input";
import ProjectDropdown from "@/components/ui/project-dropdown";
import ProjectTooltip from "@/components/ui/project-tooltip";
import EntityEditDialog from "@/components/ui/entity-edit-dialog";
import { Button } from "@/components/ui/button";
import { CollectionTable, CollectionTableHead, CollectionTableBody, CollectionMobileList, CollectionMobileCard, CollectionState, collectionRowClass } from "@/components/ui/collection-display";

type Gateway={id?:number;name:string;description:string;api_host:string;api_port:number;api_username:string;api_tls:boolean;ovpn_host:string;ovpn_port:number;ovpn_protocol:string;tunnel_cidr:string;certificate_name:string;ppp_profile:string;server_tunnel_address:string;enabled:boolean;has_api_password?:boolean};
const empty:Gateway={name:"",description:"",api_host:"",api_port:8729,api_username:"",api_tls:true,ovpn_host:"",ovpn_port:1194,ovpn_protocol:"tcp",tunnel_cidr:"",certificate_name:"",ppp_profile:"",server_tunnel_address:"",enabled:false};
const endpoint="/api/admin/platform-settings/ovpn-gateways";
export default function ConnectionServersPage(){
 const {isMasterAdmin,loading:authLoading}=useAuth();
 const [rows,setRows]=useState<Gateway[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[form,setForm]=useState<Gateway|null>(null),[password,setPassword]=useState(""),[saving,setSaving]=useState(false),[readOnly,setReadOnly]=useState(false),[formError,setFormError]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch(endpoint,{credentials:"include"}),j=await r.json();if(!r.ok)throw new Error(j.message);setRows(j.gateways);}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل الخوادم.");}finally{setLoading(false);}}
 useEffect(()=>{if(isMasterAdmin)void load();},[isMasterAdmin]);
 function open(row:Gateway,view=false){setForm({...row});setPassword("");setFormError("");setReadOnly(view);}
 function close(){if(saving)return;setForm(null);setPassword("");}
 function set<K extends keyof Gateway>(key:K,value:Gateway[K]){setForm(x=>x?{...x,[key]:value}:x);}
 async function save(){if(!form)return;setSaving(true);setFormError("");try{const r=await fetch(endpoint+(form.id?`/${form.id}`:""),{method:form.id?"PUT":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,api_password:password||undefined})}),j=await r.json();if(!r.ok)throw new Error(j.message);setForm(null);setPassword("");setNotice("تم حفظ الخادم بنجاح.");await load();}catch(e){setFormError(e instanceof Error?e.message:"تعذر الحفظ.");}finally{setSaving(false);}}
 const visible=rows.filter(r=>(filter==="all"||String(r.enabled)===filter)&&`${r.name} ${r.ovpn_host} ${r.api_host}`.toLowerCase().includes(query.toLowerCase()));
 if(authLoading)return <CollectionState>جارٍ التحميل...</CollectionState>;
 if(!isMasterAdmin)return <CollectionState>هذه الصفحة خاصة بالمدير الرئيسي للمنصة.</CollectionState>;
 const actions=(r:Gateway)=><div className="flex gap-2" onClick={e=>e.stopPropagation()}><ProjectTooltip label="عرض الخادم"><Button variant="outline" size="icon" aria-label="عرض الخادم" onClick={()=>open(r,true)}><Eye className="text-blue-500"/></Button></ProjectTooltip><ProjectTooltip label="تعديل الخادم"><Button variant="outline" size="icon" aria-label="تعديل الخادم" onClick={()=>open(r)}><Pencil className="text-amber-500"/></Button></ProjectTooltip></div>;
 const field=(key:keyof Gateway,label:string,placeholder="",numeric=false)=><label key={key} className="space-y-2 text-xs font-medium"><span>{label}</span><ProjectInput disabled={readOnly||saving} type="text" inputMode={numeric?"numeric":undefined} dir={key==="name"||key==="description"?"rtl":"ltr"} maxLength={numeric?5:253} value={String(form?.[key]??"")} placeholder={placeholder} onChange={e=>set(key,(numeric?Number(e.target.value.replace(/[^0-9]/g,"")):e.target.value) as never)}/></label>;
 return <div dir="rtl" className="space-y-5 text-slate-800 dark:text-slate-200">
 <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Server className="text-blue-500"/>خوادم الاتصال</h1><p className="mt-1 text-sm text-slate-500">بوابات OpenVPN المركزية لبيئات الكلاود.</p></div><Button onClick={()=>open(empty)}><Plus/>إضافة خادم</Button></div>
 <section className="rl-surface grid gap-3 rounded-[22px] bg-white p-4 dark:bg-[#0d243b] sm:grid-cols-[1fr_200px]"><ProjectInput aria-label="البحث عن خادم" placeholder="بحث بالاسم أو العنوان..." value={query} onChange={e=>setQuery(e.target.value)}/><ProjectDropdown value={filter} onChange={setFilter} options={[{value:"all",label:"جميع الخوادم"},{value:"true",label:"مفعّل"},{value:"false",label:"موقوف"}]}/></section>
 {notice&&<p role="status" className="text-sm text-emerald-600">{notice}</p>}
 {loading?<CollectionState>جارٍ تحميل الخوادم...</CollectionState>:error?<CollectionState><p role="alert">{error}</p><Button variant="outline" className="mt-3" onClick={load}>إعادة المحاولة</Button></CollectionState>:!visible.length?<CollectionState>{rows.length?"لا توجد نتائج مطابقة.":"لم تتم إضافة خوادم اتصال بعد."}</CollectionState>:<><CollectionTable><CollectionTableHead><tr>{["الخادم","عنوان OpenVPN","التفعيل","اتصال الإدارة","الإجراءات"].map(h=><th key={h} className="p-4">{h}</th>)}</tr></CollectionTableHead><CollectionTableBody>{visible.map(r=><tr key={r.id} className={collectionRowClass()} onClick={()=>open(r,true)}><td className="p-4 font-semibold">{r.name}</td><td className="p-4"><bdi>{r.ovpn_host}:{r.ovpn_port}</bdi></td><td className="p-4">{r.enabled?"مفعّل":"موقوف"}</td><td className="p-4 text-slate-400">لم يُفحص</td><td className="p-4">{actions(r)}</td></tr>)}</CollectionTableBody></CollectionTable><CollectionMobileList>{visible.map(r=><CollectionMobileCard key={r.id} onOpen={()=>open(r,true)}><div className="flex items-center justify-between gap-2"><strong>{r.name}</strong>{actions(r)}</div><p className="mt-3 text-sm"><bdi>{r.ovpn_host}:{r.ovpn_port}</bdi></p><p className="mt-2 text-xs text-slate-500">{r.enabled?"مفعّل":"موقوف"} · اتصال الإدارة: لم يُفحص</p></CollectionMobileCard>)}</CollectionMobileList></>}
 {form&&<EntityEditDialog title={readOnly?"تفاصيل الخادم":form.id?"تعديل خادم الاتصال":"إضافة خادم اتصال"} description="حفظ الإعدادات لا يغيّر إعداد MikroTik؛ فحص الاتصال وتجهيز الأنفاق في المرحلة التالية." onClose={close} footer={<><Button variant="outline" disabled={saving} onClick={close}>إغلاق</Button>{!readOnly&&<Button disabled={saving} onClick={save}><Save/>{saving?"جارٍ الحفظ...":"حفظ الخادم"}</Button>}</>}>
 <div className="space-y-5"><fieldset disabled={saving||readOnly} className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 text-sm font-bold">البيانات الأساسية</legend>{field("name","اسم الخادم")}{field("description","الوصف — اختياري")}</fieldset>
 <div className="space-y-2"><span className="text-xs">تخصيص اتصالات جديدة</span>{readOnly?<p>{form.enabled?"مفعّل":"موقوف"}</p>:!saving&&<ProjectDropdown value={String(form.enabled)} onChange={v=>set("enabled",v==="true")} options={[{value:"false",label:"موقوف"},{value:"true",label:"مفعّل"}]}/>}<p className="text-xs text-slate-500">الإيقاف يمنع التخصيص الجديد؛ لا يقطع الأنفاق القائمة.</p></div>
 <fieldset disabled={saving||readOnly} className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 text-sm font-bold">اتصال الإدارة — API</legend>{field("api_host","العنوان")}{field("api_port","المنفذ","8729",true)}{field("api_username","اسم المستخدم")}<label className="space-y-2 text-xs"><span>كلمة المرور {form.has_api_password?"— محفوظة؛ اترك فارغة للإبقاء عليها":""}</span>{readOnly?<p>{form.has_api_password?"محفوظة ومشفّرة":"لم تُحفظ"}</p>:<ProjectInput type="password" autoComplete="new-password" value={password} maxLength={512} onChange={e=>setPassword(e.target.value)}/>}</label></fieldset>
 <div className="space-y-2"><span className="text-xs">اتصال API</span>{readOnly?<p>{form.api_tls?"TLS":"دون TLS"}</p>:!saving&&<ProjectDropdown value={String(form.api_tls)} onChange={v=>set("api_tls",v==="true")} options={[{value:"true",label:"API مع TLS"},{value:"false",label:"API دون TLS"}]}/>}</div>
 <fieldset disabled={saving||readOnly} className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 text-sm font-bold">خادم OpenVPN</legend>{field("ovpn_host","العنوان العام أو الدومين")}{field("ovpn_port","المنفذ","1194",true)}{field("ppp_profile","اسم PPP Profile")}{field("certificate_name","اسم شهادة الخادم")}{field("server_tunnel_address","عنوان طرف الخادم","10.80.0.1")}{field("tunnel_cidr","نطاق الأنفاق","10.80.0.0/16")}<p className="text-xs text-slate-500 sm:col-span-2">البروتوكول الحالي: TCP. أدخل أسماء الـProfile والشهادة الموجودة على MikroTik.</p></fieldset>
 {formError&&<p role="alert" className="text-sm text-red-500">{formError}</p>}</div>
 </EntityEditDialog>}
 </div>;
}
