import {getInfrastructureHealth,saveInfrastructureSelection,runInfrastructureHealth} from '../../controllers/infrastructure-health.controller';
import {listRadiusServers,saveRadiusServer,radiusServerHealth} from '../../controllers/radius-servers.controller';
import { getLocalHostingSettings, saveLocalHostingSettings } from '../../controllers/local-hosting.controller';
import {listDatabaseServers,inspectDatabaseServer,saveDatabaseServer,databaseServerHealth,setDatabaseServerAdmission} from '../../controllers/database-servers.controller';
import {getSshConnection,inspectSshConnection,saveSshConnection,createSshTicket} from '../../services/ssh-terminal.service';
import { env } from '../../config/env';
import { getOvpnSettings, updateOvpnSettings, inspectOvpnGateway, applyOvpnGateway, getOvpnGatewayHealth, selectOvpnHealthDashboard } from '../../controllers/ovpn-settings.controller';
import { Router } from 'express';
import { getContactPaymentSettingsController, updateContactPaymentSettingsController } from '../../controllers/platform-settings.controller';
import { authenticate, requireAccountType } from '../../middleware/auth.middleware';
const router=Router();
router.use(authenticate,requireAccountType('master_admin'));
router.get('/infrastructure-health',getInfrastructureHealth);
router.use('/infrastructure-health',(req,res,next)=>{
 if(req.method!=='GET'&&req.headers.origin!==new URL(env.FRONTEND_URL).origin)return res.status(403).json({message:'مصدر طلب فحص البنية التحتية غير مصرح.'});
 return next();
});
router.put('/infrastructure-health',saveInfrastructureSelection);
router.post('/infrastructure-health/check',runInfrastructureHealth);
router.use('/database-servers/:id/ssh', (req,res,next)=>{
 if(req.method==='GET')return next();
 if(req.headers.origin!==new URL(env.FRONTEND_URL).origin)return res.status(403).json({message:'مصدر طلب SSH غير مصرح.'});
 return next();
});
router.get('/database-servers/:id/ssh',getSshConnection);
router.post('/database-servers/:id/ssh/inspect',inspectSshConnection);
router.put('/database-servers/:id/ssh',saveSshConnection);
router.post('/database-servers/:id/ssh/ticket',createSshTicket);
router.get('/database-servers',listDatabaseServers);
router.get('/database-servers/:id/health',databaseServerHealth);
router.put('/database-servers/:id/admission',setDatabaseServerAdmission);
router.post('/database-servers/inspect',inspectDatabaseServer);
router.post('/database-servers/:id/inspect',inspectDatabaseServer);
router.post('/database-servers',saveDatabaseServer);
router.put('/database-servers/:id',saveDatabaseServer);
router.use('/radius-servers',(req,res,next)=>{
 if(req.method!=='GET'&&req.headers.origin!==new URL(env.FRONTEND_URL).origin)return res.status(403).json({message:'مصدر طلب FreeRADIUS غير مصرح.'});
 return next();
});
router.get('/radius-servers',listRadiusServers);
router.post('/radius-servers',saveRadiusServer);
router.put('/radius-servers/:id',saveRadiusServer);
router.post('/radius-servers/:id/health',radiusServerHealth);
router.get('/local-hosting',getLocalHostingSettings);
router.put('/local-hosting',(req,res,next)=>{
 if(req.headers.origin!==new URL(env.FRONTEND_URL).origin)return res.status(403).json({message:'مصدر طلب إعدادات الاستضافة غير مصرح.'});
 return next();
},saveLocalHostingSettings);
router.get('/contact-payment',getContactPaymentSettingsController);
router.put('/contact-payment',updateContactPaymentSettingsController);
router.get('/ovpn-gateways',getOvpnSettings);
router.get('/ovpn-gateways/:id/health',getOvpnGatewayHealth);
router.put('/ovpn-gateways/:id/dashboard-health',selectOvpnHealthDashboard);
router.post('/ovpn-gateways/inspect',inspectOvpnGateway);
router.post('/ovpn-gateways/:id/inspect',inspectOvpnGateway);
router.post('/ovpn-gateways/:id/apply',applyOvpnGateway);
router.post('/ovpn-gateways',updateOvpnSettings);
router.put('/ovpn-gateways/:id',updateOvpnSettings);
export default router;
