import { getOvpnSettings, updateOvpnSettings, inspectOvpnGateway, applyOvpnGateway } from '../../controllers/ovpn-settings.controller';
import { Router } from 'express';
import { getContactPaymentSettingsController, updateContactPaymentSettingsController } from '../../controllers/platform-settings.controller';
import { authenticate, requireAccountType } from '../../middleware/auth.middleware';
const router=Router();
router.use(authenticate,requireAccountType('master_admin'));
router.get('/contact-payment',getContactPaymentSettingsController);
router.put('/contact-payment',updateContactPaymentSettingsController);
router.get('/ovpn-gateways',getOvpnSettings);
router.post('/ovpn-gateways/inspect',inspectOvpnGateway);
router.post('/ovpn-gateways/:id/inspect',inspectOvpnGateway);
router.post('/ovpn-gateways/:id/apply',applyOvpnGateway);
router.post('/ovpn-gateways',updateOvpnSettings);
router.put('/ovpn-gateways/:id',updateOvpnSettings);
export default router;
