import {listDatabaseServers,inspectDatabaseServer,saveDatabaseServer,databaseServerHealth,setDatabaseServerAdmission} from '../../controllers/database-servers.controller';
import { getOvpnSettings, updateOvpnSettings, inspectOvpnGateway, applyOvpnGateway, getOvpnGatewayHealth, selectOvpnHealthDashboard } from '../../controllers/ovpn-settings.controller';
import { Router } from 'express';
import { getContactPaymentSettingsController, updateContactPaymentSettingsController } from '../../controllers/platform-settings.controller';
import { authenticate, requireAccountType } from '../../middleware/auth.middleware';
const router=Router();
router.use(authenticate,requireAccountType('master_admin'));
router.get('/database-servers',listDatabaseServers);
router.get('/database-servers/:id/health',databaseServerHealth);
router.put('/database-servers/:id/admission',setDatabaseServerAdmission);
router.post('/database-servers/inspect',inspectDatabaseServer);
router.post('/database-servers/:id/inspect',inspectDatabaseServer);
router.post('/database-servers',saveDatabaseServer);
router.put('/database-servers/:id',saveDatabaseServer);
router.get('/contact-payment',getContactPaymentSettingsController);
router.put('/contact-payment',updateContactPaymentSettingsController);
router.get('/ovpn-gateways',getOvpnSettings);
router.get('/ovpn-gateways/:id/health',getOvpnGatewayHealth);
router.put('/ovpn-gateways/:id/dashboard-health',selectOvpnHealthDashboard);
router.post('/ovpn-gateways/inspect',inspectOvpnGateway);
router.post('/ovpn-gateways/:id/inspect',inspectOvpnGateway);
router.post('/ovpn-gateways/:id/apply',applyOvpnGateway);
router.post('/ovpn-gateways',updateOvpnSettings);
router.put('/ovpn-gateways/:id',updateOvpnSettings);
export default router;
