import type {Response} from 'express';
import type {AuthenticatedRequest} from '../middleware/auth.middleware';
import {db} from '../config/db';
import {writeAuditLog} from '../services/audit.service';
import {EnvironmentRequestError} from '../services/subscription-environment.service';
export async function requestEnvironmentNotification(req:AuthenticatedRequest,res:Response){const id=Number(req.params.id);if(!Number.isSafeInteger(id)||id<1)return res.status(400).json({message:'رقم الاشتراك غير صالح.'});let conn;
 try{conn=await db.pool.getConnection();await conn.beginTransaction();const [rows]:any=await conn.query(`SELECT e.id environment_id,e.tenant_id,e.status,e.system_url,s.id subscription_id,s.status subscription_status,s.expires_at,l.status license_status,h.database_status,h.radius_status,h.reported_at FROM payment_orders p JOIN subscriptions s ON s.id=p.subscription_id AND s.tenant_id=p.tenant_id JOIN tenant_environments e ON e.tenant_id=s.tenant_id JOIN subscription_licenses l ON l.tenant_id=s.tenant_id AND l.subscription_id=s.id JOIN tenant_environment_status h ON h.environment_id=e.id WHERE p.id=? AND p.status IN ('paid','completed') FOR UPDATE`,[id]);const e=rows[0];if(!e||e.status!=='ready'||e.subscription_status!=='active'||e.license_status!=='active'||!e.system_url||!e.expires_at||new Date(e.expires_at).getTime()<=Date.now())throw new EnvironmentRequestError(409,'يجب تفعيل البيئة والاشتراك والرخصة وتجهيز رابط واجهة العميل أولًا.');
 if(e.database_status!=='healthy'||e.radius_status!=='healthy'||!e.reported_at||Date.now()-new Date(e.reported_at).getTime()<0||Date.now()-new Date(e.reported_at).getTime()>=90000)throw new EnvironmentRequestError(409,'يلزم فحص حديث وسليم لقاعدة البيانات وخدمة RADIUS قبل الإرسال.');
 const [jobs]:any=await conn.query("SELECT id FROM environment_provisioning_jobs WHERE environment_id=? AND subscription_id=? AND status='success' LIMIT 1",[e.environment_id,e.subscription_id]);if(!jobs.length)throw new EnvironmentRequestError(409,'لم يكتمل تجهيز البيئة بنجاح.');
 const [notifications]:any=await conn.query('SELECT * FROM environment_notifications WHERE environment_id=? AND subscription_id=? ORDER BY id DESC LIMIT 1 FOR UPDATE',[e.environment_id,e.subscription_id]);const n=notifications[0];if(!n)throw new EnvironmentRequestError(409,'لم تُجهّز بيانات الدخول ورقم المستلم الموثق بعد.');if(n.status==='sent'){await conn.commit();return res.json({status:'sent',message:'سبق إرسال بيانات التفعيل؛ لن تُرسل بيانات دخول قديمة مرة أخرى.'});}
 if(!n.initial_username||!n.initial_password_encrypted||!n.credentials_expires_at||new Date(n.credentials_expires_at).getTime()<=Date.now()||!/^\+?[1-9][0-9]{7,14}$/.test(n.recipient_phone))throw new EnvironmentRequestError(409,'بيانات الإرسال غير مكتملة أو انتهت صلاحية بيانات الدخول.');
 if(process.env.ENVIRONMENT_NOTIFICATION_WORKER_ENABLED!=='true')throw new EnvironmentRequestError(503,'خدمة إرسال بيانات البيئة غير مفعلة؛ لم يتم إرسال رسالة للعميل.');
 if(n.status==='failed'){await conn.query("UPDATE environment_notifications SET status='pending',next_attempt_at=CURRENT_TIMESTAMP,lock_token=NULL,locked_until=NULL,error_code=NULL,error_message=NULL WHERE id=?",[n.id]);await writeAuditLog(req,{actionCode:'UPDATE',entityTypeCode:'ENVIRONMENT_NOTIFICATION',entityId:n.id,tenantId:e.tenant_id,description:'إعادة طلب إرسال بيانات تفعيل البيئة',metadata:{environmentId:e.environment_id,subscriptionId:e.subscription_id}},conn);}
 await conn.commit();res.status(202).json({status:n.status==='sending'?'sending':'pending',message:'طلب الإرسال مسجل؛ تأكيد التسليم ينتظر استجابة خدمة الرسائل.'});
 }catch(error){await conn?.rollback();res.status(error instanceof EnvironmentRequestError?error.status:500).json({message:error instanceof EnvironmentRequestError?error.message:'تعذر تسجيل طلب الإرسال.'});}finally{conn?.release();}}
