import { Response } from 'express';
import { db } from '../config/db';
import { AuthenticatedRequest } from '../middleware/auth.middleware';
import { writeAuditLog } from '../services/audit.service';

const GROUP='contact_payment';
const KEYS=['contact_name','whatsapp_number','whatsapp_enabled','whatsapp_button_text','whatsapp_message_template','payment_instructions'];
const defaults:any={contact_name:'',whatsapp_number:'',whatsapp_enabled:true,whatsapp_button_text:'التواصل عبر واتساب لإتمام الدفع',whatsapp_message_template:'مرحبًا، أرغب بإتمام اشتراكي في Radius Lord. كود الدفع: {{payment_code}}',payment_instructions:''};
function normalize(rows:any[]){const out={...defaults};for(const r of rows){if(!KEYS.includes(r.setting_key))continue;out[r.setting_key]=r.value_type==='boolean'?String(r.setting_value)==='1':(r.setting_value??'')}return out;}
export async function getContactPaymentSettingsController(req:AuthenticatedRequest,res:Response){try{const [rows]=await db.query("SELECT setting_key,setting_value,value_type FROM platform_settings WHERE setting_group=?",[GROUP]);return res.json({success:true,settings:normalize(rows as any[])});}catch(e){console.error(e);return res.status(500).json({success:false,message:'تعذر تحميل إعدادات التواصل والدفع.'});}}
export async function getPublicContactPaymentSettingsController(req:AuthenticatedRequest,res:Response){try{const [rows]=await db.query("SELECT setting_key,setting_value,value_type FROM platform_settings WHERE setting_group=? AND is_public=1",[GROUP]);return res.json({success:true,settings:normalize(rows as any[])});}catch(e){console.error(e);return res.status(500).json({success:false,message:'تعذر تحميل معلومات التواصل.'});}}
export async function updateContactPaymentSettingsController(req:AuthenticatedRequest,res:Response){try{const b=req.body??{};const values:any={contact_name:String(b.contact_name??'').trim(),whatsapp_number:String(b.whatsapp_number??'').replace(/[^0-9+]/g,''),whatsapp_enabled:b.whatsapp_enabled?'1':'0',whatsapp_button_text:String(b.whatsapp_button_text??'').trim(),whatsapp_message_template:String(b.whatsapp_message_template??'').trim(),payment_instructions:String(b.payment_instructions??'').trim()};if(values.whatsapp_number&& !/^\+?[1-9]\d{6,14}$/.test(values.whatsapp_number))return res.status(400).json({success:false,message:'رقم واتساب غير صالح. استخدم الصيغة الدولية.'});if(!values.whatsapp_button_text)return res.status(400).json({success:false,message:'أدخل نص زر واتساب.'});if(!values.whatsapp_message_template.includes('{{payment_code}}'))return res.status(400).json({success:false,message:'قالب الرسالة يجب أن يحتوي {{payment_code}}.'});for(const key of KEYS){await db.query("INSERT INTO platform_settings (setting_group,setting_key,setting_value,value_type,is_public,updated_by_master_admin_id) VALUES (?,?,?, ?,1,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by_master_admin_id=VALUES(updated_by_master_admin_id)",[GROUP,key,values[key],key==='whatsapp_enabled'?'boolean':(key.includes('template')||key==='payment_instructions'?'text':'string'),req.auth!.accountId]);}await writeAuditLog({actorType:'master_admin',actorId:req.auth!.accountId,action:'update',entityType:'platform_settings',entityId:null,description:'تحديث إعدادات التواصل والدفع',req});return res.json({success:true,settings:{...values,whatsapp_enabled:values.whatsapp_enabled==='1'}});}catch(e){console.error(e);return res.status(500).json({success:false,message:'تعذر حفظ إعدادات التواصل والدفع.'});}}
