"use client";
import {useEffect,useRef,useState} from "react";
import {Database,Activity,Clock,RefreshCw,Network,ShieldCheck} from "lucide-react";
import ProjectResourceMetric from "@/components/ui/project-resource-metric";
import ProjectButton from "@/components/ui/project-button";
import ProjectTooltip from "@/components/ui/project-tooltip";
type Health={checkedAt:string;version:string;maxConnections:number;metrics:Record<string,number>;networkDatabases:number;appReserved:number;radiusReserved:number;appBudget:number;radiusBudget:number};
export default function DatabaseHealthCard({serverId,name}:{serverId:number;name:string}){const [data,setData]=useState<Health|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);const refreshRef=useRef(()=>{});
 useEffect(()=>{let disposed=false,pending=false;const controller=new AbortController();setData(null);setError("");async function refresh(){if(disposed||pending)return;pending=true;setBusy(true);try{const r=await fetch(`/api/admin/platform-settings/database-servers/${serverId}/health`,{credentials:"include",cache:"no-store",signal:controller.signal}),j=await r.json();if(!r.ok)throw new Error(j.message);if(!disposed){setData(j);setError("");}}catch(e){if(!disposed)setError(e instanceof Error?e.message:"فشل اتصال الخادم.");}finally{pending=false;if(!disposed)setBusy(false);}}refreshRef.current=()=>void refresh();void refresh();const timer=setInterval(()=>{if(document.visibilityState==="visible")void refresh();},30000);const visible=()=>{if(document.visibilityState==="visible")void refresh();};document.addEventListener("visibilitychange",visible);return()=>{disposed=true;controller.abort();clearInterval(timer);document.removeEventListener("visibilitychange",visible);};},[serverId]);
 const m=data?.metrics||{},percent=data&&data.maxConnections>0?m.Threads_connected/data.maxConnections*100:null;
 return <section className="ui-state-enter rounded-[20px] border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-[#203044] sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold"><Database className="text-violet-500"/>صحة {name}</h2><p className="mt-1 text-xs text-slate-500">تحديث كل 30 ثانية · {data?`آخر قراءة: ${new Date(data.checkedAt).toLocaleString("ar")}`:"بانتظار الفحص"}</p></div><ProjectTooltip label="تحديث صحة خادم قاعدة البيانات"><ProjectButton variant="secondary" disabled={busy} onClick={()=>refreshRef.current()}><RefreshCw className={busy?"motion-safe:animate-spin":""}/>تحديث</ProjectButton></ProjectTooltip></div>
 {error?<p role="alert" className="ui-field-warning mt-4 rounded-[14px] bg-red-50 p-3 text-sm text-red-600 dark:bg-red-500/10">{error}{data&&" القيم المعروضة من آخر قراءة ناجحة."}</p>:<p role="status" className="mt-3 text-xs text-emerald-600 dark:text-emerald-300">{data?"نجح الاتصال وقراءة حالة MySQL":"جارٍ فحص الاتصال..."}</p>}
 <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ProjectResourceMetric name="الاتصالات الحالية" icon={Network} value={data?String(m.Threads_connected):"—"} detail={data?`الحد الأقصى للخادم: ${data.maxConnections}`:"بانتظار بيانات MySQL"} percent={percent} refreshing={busy} stale={Boolean(error)} tone="blue"/><ProjectResourceMetric name="قواعد الشبكات" icon={Database} value={data?String(data.networkDatabases):"—"} detail="القواعد المسجلة على هذا الخادم" percent={null} refreshing={busy} stale={Boolean(error)} tone="violet"/><ProjectResourceMetric name="استعلامات قيد التنفيذ" icon={Activity} value={data?String(m.Threads_running):"—"} detail={data?`استعلامات بطيئة منذ بدء MySQL: ${m.Slow_queries??"غير متاح"}`:"بانتظار البيانات"} percent={null} refreshing={busy} stale={Boolean(error)} tone="amber"/><ProjectResourceMetric name="مدة تشغيل MySQL" icon={Clock} value={data?`${Math.floor((m.Uptime||0)/3600)} ساعة`:"—"} detail={data?`إصدار MySQL: ${data.version}`:"بانتظار البيانات"} percent={null} refreshing={busy} stale={Boolean(error)} tone="cyan"/></div>
 {data&&<p className="mt-4 flex flex-wrap items-center gap-2 text-xs leading-6 text-slate-500"><ShieldCheck className="h-4 w-4 text-emerald-500"/>الاتصالات المحجوزة للتطبيق: {data.appReserved} من {data.appBudget} · RADIUS: {data.radiusReserved} من {data.radiusBudget}</p>}<p className="mt-2 text-xs leading-6 text-slate-400">المحجوزة هي حدود حسابات الشبكات، وليست عدد اتصالاتها الحالية. مؤشرات CPU وRAM والتخزين تحتاج ربط مراقبة نظام الخادم.</p>
 </section>;
}
