"use client";
import {useState} from "react";
import {CodeXml,Copy,KeyRound,Check,ArrowRight} from "lucide-react";
import ProjectInput from "@/components/ui/project-input";
import ProjectButton from "@/components/ui/project-button";
import ProjectTooltip from "@/components/ui/project-tooltip";
export default function DatabaseAccountScript({onClose,onUse,serverName,serverHost,defaultUsername="lord_provisioner"}:{onClose:()=>void;onUse:(username:string,password:string)=>void;serverName?:string;serverHost?:string;defaultUsername?:string}){
 const [username,setUsername]=useState(defaultUsername),[host,setHost]=useState(""),[password,setPassword]=useState(""),[script,setScript]=useState(""),[error,setError]=useState(""),[copied,setCopied]=useState(false);
 function reset(){setScript("");setCopied(false);setError("");}
 function generatePassword(){const data=new Uint8Array(24);crypto.getRandomValues(data);reset();setPassword("Rl!9"+Array.from(data,n=>n.toString(16).padStart(2,"0")).join(""));}
 function generate(){setError("");setCopied(false);if(!/^[a-zA-Z][a-zA-Z0-9_]{0,31}$/.test(username)){setError("اسم الحساب يبدأ بحرف ويحتوي حروفًا إنجليزية وأرقامًا وشرطة سفلية، حتى 32 محرفًا.");return;}
 if(!host||host.length>253||!/^[a-zA-Z0-9][a-zA-Z0-9.:-]*$/.test(host)){setError("أدخل عنوان مصدر اتصال الباك إند كما يراه MySQL، أو localhost إذا كانا على الخادم نفسه. لا تستخدم %.");return;}
 if(!/^[a-zA-Z0-9!@#$%^&*()+.=:?~\-]{4,128}$/.test(password)){setError("استخدم كلمة مرور من 4 إلى 128 محرفًا دون مسافات أو علامات اقتباس أو شرطة عكسية، أو اضغط توليد كلمة مرور.");return;}
 const account=`'${username}'@'${host}'`,rights="SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, REFERENCES, CREATE ROUTINE, ALTER ROUTINE, EXECUTE";
 setScript(["-- MySQL 8: run with an administrative account.","-- Creates a NEW provisioning account; stops if it already exists.","-- Host is the BACKEND source address seen by MySQL.","-- Schema grants use MySQL database patterns (partial_revokes must be OFF).",`CREATE USER ${account} IDENTIFIED BY '${password}';`,`GRANT CREATE USER ON *.* TO ${account};`,`GRANT ${rights} ON \`rl\\_tenant\\_%\`.* TO ${account} WITH GRANT OPTION;`,`GRANT ${rights} ON \`rl\\_probe\\_%\`.* TO ${account} WITH GRANT OPTION;`,"-- Return to Radius Lord and run the connection/permissions check."].join("\n"));}
 async function copy(){try{await navigator.clipboard.writeText(script);setCopied(true);}catch{setError("تعذر النسخ التلقائي. حدد نص السكربت وانسخه يدويًا.");}}
 return <section className="ui-state-enter rounded-[20px] border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-[#203044] sm:p-6"><div className="flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 font-semibold"><CodeXml className="text-violet-500"/>توليد سكربت حساب التجهيز{serverName?` — ${serverName}`:""}</h2><ProjectTooltip label="إغلاق مولد السكربت"><ProjectButton variant="back" size="icon" aria-label="إغلاق مولد السكربت" onClick={onClose}><ArrowRight/></ProjectButton></ProjectTooltip></div>{serverHost&&<p className="mt-2 text-xs text-slate-500">الخادم المستهدف: <bdi>{serverHost}</bdi></p>}<p className="mt-3 text-sm leading-7 text-slate-500">نفّذ السكربت بحساب MySQL إداري، عبر تبويبة SQL في phpMyAdmin أو Terminal الخادم. توليد السكربت لا ينشئ الحساب تلقائيًا ولا يعالج تعذر دخول الحساب الإداري.</p>
 <form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();generate();}}><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm"><span className="block">اسم مستخدم التجهيز</span><ProjectInput required maxLength={32} value={username} onChange={e=>{reset();setUsername(e.target.value);}}/></label><label className="space-y-2 text-sm"><span className="block">عنوان جهاز الباك إند (مصدر الاتصال)</span><ProjectInput required placeholder="مثال: 192.168.88.6" maxLength={253} value={host} onChange={e=>{reset();setHost(e.target.value.trim());}}/></label><label className="space-y-2 text-sm sm:col-span-2"><span className="block">كلمة المرور</span><div className="flex flex-col gap-2 sm:flex-row"><ProjectInput required type="password" autoComplete="new-password" minLength={4} maxLength={128} value={password} onChange={e=>{reset();setPassword(e.target.value);}}/><ProjectTooltip label="توليد كلمة مرور عشوائية قوية"><ProjectButton type="button" variant="secondary" className="shrink-0" onClick={generatePassword}><KeyRound className="text-amber-500"/>توليد كلمة مرور</ProjectButton></ProjectTooltip></div></label></div>{error&&<p role="alert" className="ui-field-warning rounded-[14px] bg-red-50 p-3 text-sm text-red-600 dark:bg-red-500/10">{error}</p>}<div className="flex justify-end"><ProjectButton type="submit"><CodeXml/>توليد السكربت</ProjectButton></div></form>
 {script&&<div className="mt-5 space-y-3"><p className="text-xs leading-6 text-slate-500">الصلاحيات محصورة بقواعد العملاء وقواعد الفحص، مع صلاحية إدارة المستخدمين اللازمة للتجهيز. السكربت يتضمن كلمة المرور؛ لا تشاركه. إذا ظهر خطأ، توقف ولا تتجاوز سطر إنشاء الحساب.</p><pre dir="ltr" tabIndex={0} className="allow-text-selection max-h-80 overflow-auto whitespace-pre rounded-[14px] bg-slate-950 p-4 text-left text-xs leading-6 text-slate-100">{script}</pre><div className="flex flex-wrap justify-end gap-2"><ProjectTooltip label="نسخ السكربت لتنفيذه على MySQL"><ProjectButton variant="secondary" onClick={()=>void copy()}>{copied?<Check className="text-emerald-500"/>:<Copy className="text-blue-500"/>}{copied?"تم النسخ":"نسخ السكربت"}</ProjectButton></ProjectTooltip><ProjectButton onClick={()=>onUse(username,password)}>استخدام البيانات في نموذج الخادم</ProjectButton></div><p className="text-xs text-slate-400">استخدام البيانات يملأ النموذج فقط. بعد تنفيذ السكربت اضغط فحص الاتصال والصلاحيات ثم احفظ الخادم.</p></div>}
 </section>;
}
