"use client";
import ProjectLoading from "@/components/ui/project-loading";

import { useEffect,useRef,useState } from "react";
import { ArrowRight,Check,Crown,Filter,RotateCcw,Server,Star,Users } from "lucide-react";
import { useRouter } from "next/navigation";
import ProjectDropdown from "@/components/ui/project-dropdown";

type DeploymentOption={id:number;deploymentTypeId:number;code:string;nameAr:string;description:string|null;price:number;isDefault:boolean;status:"active"|"inactive"};
type Addon={id:number;deploymentTypeId:number;code:string;nameAr:string;description:string|null;price:number;status:"active"|"inactive"};
type Plan={id:number;name:string;durationMonths:number;maxTenants:number;maxSubscribers:number;maxNas:number;price:number;currency:string;description:string|null;isFeatured:boolean;status:"active"|"inactive"|"disabled";deploymentOptions:DeploymentOption[];addons:Addon[]};

export default function CustomerPlansPage(){
 const router=useRouter(),[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[checkoutLoading,setCheckoutLoading]=useState(false),[checkoutError,setCheckoutError]=useState(""),[selected,setSelected]=useState<Record<number,number>>({}),[selectedAddons,setSelectedAddons]=useState<Record<number,number[]>>({}),[duration,setDuration]=useState("all"),[hosting,setHosting]=useState("all"),[capacity,setCapacity]=useState("all"),[filtersOpen,setFiltersOpen]=useState(false),[chosenPlanId,setChosenPlanId]=useState<number|null>(null); const resultsRef=useRef<HTMLElement>(null),summaryRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{fetch("/api/admin/payment-plans/available",{credentials:"include",cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>setPlans((d.plans??[]).filter((p:Plan)=>p.status==="active"))).catch(()=>setError("تعذر تحميل الخطط المتاحة حالياً.")).finally(()=>setLoading(false))},[]);
 const durations=Array.from(new Set(plans.map(p=>p.durationMonths))).sort((a,b)=>a-b);
 const hostingTypes=Array.from(new Map(plans.flatMap(p=>(p.deploymentOptions??[]).filter(o=>o.status==="active").map(o=>[o.code,o.nameAr] as const))).entries());
 const filtered=plans.filter(p=>(duration==="all"||p.durationMonths===Number(duration))&&(hosting==="all"||(p.deploymentOptions??[]).some(o=>o.status==="active"&&o.code===hosting))&&(capacity==="all"||(capacity==="small"?p.maxSubscribers>0&&p.maxSubscribers<=500:capacity==="medium"?p.maxSubscribers>500&&p.maxSubscribers<=2000:p.maxSubscribers===0||p.maxSubscribers>2000)));
 const resetFilters=()=>{setDuration("all");setHosting("all");setCapacity("all")};
 const filterActive=duration!=="all"||hosting!=="all"||capacity!=="all";
 const chosenPlan=plans.find(p=>p.id===chosenPlanId)??null;
 const chosenDeployment=chosenPlan?chosenPlan.deploymentOptions.find(o=>o.id===(selected[chosenPlan.id]??chosenPlan.deploymentOptions.find(x=>x.isDefault)?.id??chosenPlan.deploymentOptions[0]?.id)):null;
 const chosenAddonItems=chosenPlan?(chosenPlan.addons??[]).filter(a=>(selectedAddons[chosenPlan.id]??[]).includes(a.id)):[];
 const chosenAddonTotal=chosenAddonItems.reduce((sum,a)=>sum+Number(a.price||0),0);
 const chosenTotal=chosenPlan?Number(chosenPlan.price||0)+chosenAddonTotal:0;
 const choosePlan=(id:number)=>{setChosenPlanId(id);setCheckoutError("");window.setTimeout(()=>summaryRef.current?.scrollIntoView({behavior:"smooth",block:"nearest"}),180)};
 const continueToPayment=async()=>{if(!chosenPlan||!chosenDeployment||checkoutLoading)return;setCheckoutLoading(true);setCheckoutError("");try{const r=await fetch("/api/billing/orders",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({planId:chosenPlan.id,deploymentOptionId:chosenDeployment.id,addonIds:chosenAddonItems.map(a=>a.id)})});const j=await r.json();if(!r.ok)throw new Error(j.message||"تعذر إنشاء طلب الدفع.");router.push(`/Dashboard/customer-payment?order=${encodeURIComponent(j.paymentOrder.paymentCode)}`);}catch(e:any){setCheckoutError(e.message||"تعذر إنشاء طلب الدفع.");setCheckoutLoading(false)}};
 useEffect(()=>{if(!filterActive||loading)return;const t=window.setTimeout(()=>resultsRef.current?.scrollIntoView({behavior:"smooth",block:"start"}),300);return()=>window.clearTimeout(t)},[duration,hosting,capacity,filterActive,loading]);
 return <div className="plans-stage relative min-h-full overflow-hidden rounded-[22px] p-4 sm:p-5" dir="rtl">
  <div className="plans-grid absolute inset-0"/><div className="plans-glow absolute inset-0"/><div className="relative z-10 mx-auto max-w-[1180px]">
   <button onClick={()=>router.push("/Dashboard")} className="inline-flex h-10 items-center gap-2 rounded-[13px] border border-[#aac6e2] bg-white/75 px-3 text-xs font-semibold text-[#17386d] backdrop-blur-xl transition hover:bg-white dark:border-white/[.12] dark:bg-white/[.06] dark:text-white"><ArrowRight className="h-4 w-4"/>العودة</button>
   <header className="mx-auto mb-4 mt-1 max-w-[700px] text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-[15px] bg-gradient-to-br from-[#1479ff] to-[#0758e9] text-white shadow-[0_12px_28px_rgba(7,88,233,.24)]"><Crown className="h-5 w-5 text-[#ffb31a]"/></div><h1 className="mt-2 text-2xl font-bold text-[#102a63] dark:text-white sm:text-3xl">اختر الخطة المناسبة لك</h1><p className="mt-1 text-xs leading-6 text-slate-500 dark:text-slate-300">قارن الخطط المتاحة حسب السعر والمدة وعدد المشتركين وأجهزة NAS، ثم اختر طريقة الاستضافة المناسبة.</p></header>
   {!loading&&!error&&plans.length>0&&<div className="mb-4">
    <div className="flex items-center justify-between gap-3"><button type="button" onClick={()=>setFiltersOpen(v=>!v)} aria-expanded={filtersOpen} className={`inline-flex h-10 items-center gap-2 rounded-[13px] border px-4 text-xs font-bold shadow-sm transition ${filtersOpen?"border-[#75aef0] bg-[#edf5ff] text-[#0758e9] dark:border-[#4d91df] dark:bg-[#1479ff]/15 dark:text-[#8dbdff]":"border-[#b9cfe4] bg-white/80 text-[#17386d] hover:border-[#8db9e8] dark:border-white/[.14] dark:bg-[#203247] dark:text-slate-100 dark:hover:border-[#4d7298]"}`}><Filter className="h-4 w-4"/>فلترة الخطط<span className="rounded-full bg-[#0758e9] px-2 py-0.5 text-[9px] text-white">{filtered.length}</span></button><span className="text-[10px] font-semibold text-slate-400">{filtered.length} من {plans.length} خطة</span></div>
    <div className={`filter-reveal grid transition-[grid-template-rows,opacity,margin] duration-500 ease-out ${filtersOpen?"mt-3 grid-rows-[1fr] opacity-100":"grid-rows-[0fr] opacity-0"}`}><div className="min-h-0 overflow-hidden"><section className="rounded-[18px] border border-[#b9cfe4] bg-white/75 p-3 shadow-[0_10px_28px_rgba(58,84,112,.08)] backdrop-blur-xl dark:border-white/[.10] dark:bg-[#182b40]/75"><div className="flex flex-wrap items-center gap-2"><ProjectDropdown compact className="min-w-[145px]" value={duration} onChange={setDuration} options={[{value:"all",label:"كل المدد"},...durations.map(v=>({value:String(v),label:v+" شهر"}))]}/><ProjectDropdown compact className="min-w-[180px]" value={hosting} onChange={setHosting} options={[{value:"all",label:"كل أنواع الاستضافة"},...hostingTypes.map(([value,label])=>({value,label}))]}/><ProjectDropdown compact className="min-w-[170px]" value={capacity} onChange={setCapacity} options={[{value:"all",label:"كل السعات"},{value:"small",label:"حتى 500 مشترك"},{value:"medium",label:"501 - 2,000 مشترك"},{value:"large",label:"أكثر من 2,000 مشترك"}]}/><button type="button" onClick={resetFilters} className="inline-flex h-9 items-center gap-1.5 rounded-[11px] border border-[#d5e2ef] bg-white px-3 text-[11px] font-semibold text-slate-500 transition hover:border-[#9fc4ec] hover:text-[#0758e9] dark:border-white/10 dark:bg-white/5 dark:text-slate-300"><RotateCcw className="h-3.5 w-3.5"/>إعادة ضبط</button></div></section></div></div>
   </div>}
   {loading?<State><ProjectLoading>جارٍ تحميل الخطط المتاحة...</ProjectLoading></State>:error?<State>{error}</State>:plans.length===0?<State>لا توجد خطط نشطة متاحة حالياً.</State>:filtered.length===0?<State>لا توجد خطط تطابق عوامل الفلترة الحالية.</State>:<section ref={resultsRef} className="scroll-mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(p=><article key={p.id} className={`group relative overflow-hidden rounded-[24px] border bg-white/82 p-5 shadow-[0_14px_38px_rgba(58,84,112,.10)] backdrop-blur-xl transition duration-300 hover:-translate-y-1 hover:shadow-[0_20px_46px_rgba(58,84,112,.16)] dark:bg-[#182b40]/85 ${chosenPlanId===p.id?"border-[#1479ff] ring-2 ring-[#1479ff]/20 shadow-[0_20px_48px_rgba(7,88,233,.16)]":p.isFeatured?"border-[#5d9ff0] ring-2 ring-[#1479ff]/10":"border-[#b9cfe4] dark:border-white/[.10]"} ${chosenPlanId!==null&&chosenPlanId!==p.id?"opacity-80":""}`}>
    {p.isFeatured&&<span className="absolute left-4 top-4 inline-flex items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-bold text-amber-600 dark:bg-amber-500/10 dark:text-amber-300"><Star className="h-3 w-3 fill-current"/>مميزة</span>}
    <div className="text-lg font-bold text-[#17386d] dark:text-white">{p.name}</div><div className="mt-2 flex items-end gap-2"><span className="text-2xl font-bold text-[#0758e9]">{p.price} {p.currency}</span><span className="pb-1 text-[11px] text-slate-400">/ {p.durationMonths} شهر</span></div>
    <div className="mt-5"><div className="mb-2 text-[11px] font-semibold text-slate-500 dark:text-slate-300">اختر طريقة الاستضافة</div><div className="space-y-2">{(p.deploymentOptions??[]).filter(o=>o.status==="active").map(o=>{const chosen=(selected[p.id]??p.deploymentOptions.find(x=>x.isDefault)?.id??p.deploymentOptions[0]?.id)===o.id;return <button type="button" key={o.id} onClick={()=>setSelected(s=>({...s,[p.id]:o.id}))} className={`w-full rounded-[14px] border p-3 text-right transition ${chosen?"border-[#1479ff] bg-[#eef6ff] ring-2 ring-[#1479ff]/10 dark:bg-[#1479ff]/10":"border-[#dbe7f2] bg-[#f8fbff] dark:border-white/[.07] dark:bg-white/[.04]"}`}><div className="flex items-center justify-between gap-3"><span className="text-xs font-semibold text-[#17386d] dark:text-white">{o.nameAr}</span>{chosen&&<Check className="h-4 w-4 text-[#0758e9]"/>}</div></button>})}</div>{(()=>{const deploymentId=selected[p.id]??p.deploymentOptions.find(x=>x.isDefault)?.id??p.deploymentOptions[0]?.id;const deployment=p.deploymentOptions.find(x=>x.id===deploymentId);const addons=(p.addons??[]).filter(a=>a.status==="active"&&a.deploymentTypeId===deployment?.deploymentTypeId);return addons.length?<div className="mt-3"><div className="mb-2 text-[11px] font-semibold text-slate-500 dark:text-slate-300">إضافات اختيارية</div>{addons.map(a=>{const checked=(selectedAddons[p.id]??[]).includes(a.id);return <button key={a.id} type="button" onClick={()=>setSelectedAddons(s=>({...s,[p.id]:checked?(s[p.id]??[]).filter(id=>id!==a.id):[...(s[p.id]??[]),a.id]}))} className="flex w-full items-start gap-2 rounded-[14px] border border-[#dbe7f2] bg-white/70 p-3 text-right dark:border-white/[.07] dark:bg-white/[.03]"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-[6px] border ${checked?"border-[#0758e9] bg-[#0758e9] text-white":"border-slate-300"}`}>{checked&&<Check className="h-3.5 w-3.5"/>}</span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2 text-xs font-semibold"><span>{a.nameAr}</span><span className="text-[#0758e9]">+{a.price} {p.currency}</span></span>{a.description&&<span className="mt-1 block text-[10px] leading-5 text-slate-400">{a.description}</span>}</span></button>})}</div>:null})()}</div>
    {p.description&&<p className="mt-3 min-h-12 text-xs leading-6 text-slate-500 dark:text-slate-300">{p.description}</p>}
    <div className="mt-4 grid grid-cols-2 gap-2"><Metric icon={Users} label="المشتركون" value={limit(p.maxSubscribers)}/><Metric icon={Server} label="NAS" value={limit(p.maxNas)}/></div>
    <button type="button" onClick={()=>choosePlan(p.id)} disabled={!(p.deploymentOptions??[]).some(o=>o.status==="active")} className={`mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-[14px] text-xs font-semibold shadow-[0_8px_20px_rgba(7,88,233,.18)] transition disabled:cursor-not-allowed disabled:opacity-50 ${chosenPlanId===p.id?"bg-emerald-600 text-white hover:bg-emerald-700":"bg-[#0758e9] text-white hover:bg-[#064dcc]"}`}><Check className="h-4 w-4"/>{chosenPlanId===p.id?"تم اختيار هذه الخطة":"اختيار هذه الخطة"}</button>
   </article>)}</section>}
   {chosenPlan&&<div ref={summaryRef} className="sticky bottom-3 z-30 mt-5 rounded-[20px] border border-[#9fc4ec] bg-white/95 p-3 shadow-[0_18px_45px_rgba(37,64,92,.20)] backdrop-blur-xl dark:border-[#3f658b] dark:bg-[#17283b]/95"><div className="flex flex-wrap items-center gap-3"><div className="min-w-[180px] flex-1"><div className="text-[10px] font-semibold text-slate-400">ملخص الخطة المختارة</div><div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1"><span className="text-sm font-bold text-[#17386d] dark:text-white">{chosenPlan.name}</span><span className="text-[11px] text-slate-500 dark:text-slate-300">{chosenDeployment?.nameAr}</span>{chosenAddonItems.length>0&&<span className="text-[10px] font-semibold text-emerald-600 dark:text-emerald-300">+ {chosenAddonItems.map(a=>a.nameAr).join("، ")}</span>}</div></div><div className="flex items-center gap-3 rounded-[14px] bg-[#f3f8fe] px-4 py-2 dark:bg-white/[.05]"><div className="text-center"><div className="text-[9px] text-slate-400">سعر الباقة</div><div className="text-xs font-bold">{chosenPlan.price} {chosenPlan.currency}</div></div>{chosenAddonTotal>0&&<><span className="text-slate-300">+</span><div className="text-center"><div className="text-[9px] text-slate-400">الإضافات</div><div className="text-xs font-bold text-emerald-600 dark:text-emerald-300">{chosenAddonTotal} {chosenPlan.currency}</div></div></>}<span className="text-slate-300">=</span><div className="text-center"><div className="text-[9px] text-slate-400">الإجمالي</div><div className="text-sm font-extrabold text-[#0758e9]">{chosenTotal} {chosenPlan.currency}</div></div></div><div className="flex flex-col items-end gap-1"><button type="button" onClick={continueToPayment} disabled={checkoutLoading} className="h-11 rounded-[14px] bg-[#0758e9] px-6 text-xs font-bold text-white shadow-[0_8px_20px_rgba(7,88,233,.22)] transition hover:bg-[#064dcc] disabled:cursor-wait disabled:opacity-60">{checkoutLoading?"جارٍ إنشاء طلب الدفع...":"متابعة للدفع والتفعيل"}</button>{checkoutError&&<span className="max-w-[260px] text-[10px] font-semibold text-red-500">{checkoutError}</span>}</div></div></div>}
  </div>
  <style jsx>{`.plans-stage{animation:plansStageIn .58s cubic-bezier(.22,.8,.25,1) both;background:linear-gradient(135deg,#f7fbff,#edf5ff 50%,#f9fbfe)}:global(.dark) .plans-stage{background:linear-gradient(135deg,#17131b,#211a25 48%,#17263a)}.plans-grid{opacity:.58;background-image:linear-gradient(rgba(64,132,211,.15) 1px,transparent 1px),linear-gradient(90deg,rgba(64,132,211,.15) 1px,transparent 1px);background-size:38px 38px;mask-image:linear-gradient(to bottom,#000,rgba(0,0,0,.45),transparent)}.plans-glow{background:radial-gradient(circle at 50% 15%,rgba(20,121,255,.15),transparent 34%)}@keyframes plansStageIn{from{opacity:0;transform:translateX(-22px) scale(.992)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){.plans-stage{animation:none}}}`}</style>
 </div>
}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rounded-[14px] border border-[#dbe7f2] bg-[#f8fbff] p-2 text-center dark:border-white/[.07] dark:bg-white/[.04]"><Icon className="mx-auto h-4 w-4 text-[#397bd5]"/><div className="mt-1 text-[10px] text-slate-400">{label}</div><div className="mt-1 truncate text-xs font-semibold">{value}</div></div>}
function State({children}:{children:React.ReactNode}){return <div className="mx-auto max-w-[680px] rounded-[22px] border border-[#bdd2e7] bg-white/75 p-8 text-center text-sm text-slate-500 backdrop-blur-xl dark:border-white/[.10] dark:bg-white/[.05] dark:text-slate-300">{children}</div>}
function limit(v:number){return v===0?"غير محدود":new Intl.NumberFormat("ar").format(v)}
