"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useTheme } from "next-themes";
import { Check,Crown,LogOut,Moon,Sun,Wifi } from "lucide-react";
import { useEffect,useState } from "react";
import { useAuth } from "@/components/auth/auth-provider";

export default function CustomerOnboardingShell({children}:{children:React.ReactNode}){
 const pathname=usePathname(),{account}=useAuth(),{theme,setTheme}=useTheme(),[mounted,setMounted]=useState(false),[loggingOut,setLoggingOut]=useState(false);
 useEffect(()=>setMounted(true),[]);
 const logout=async()=>{if(loggingOut)return;setLoggingOut(true);try{await fetch("/api/auth/logout",{method:"POST",credentials:"include"})}finally{window.location.replace("/login")}};
 const isPlans=pathname.includes("customer-plans");
 const isPayment=pathname.includes("customer-payment");
 return <div className="customer-onboarding flex h-dvh min-h-0 flex-col overflow-hidden bg-[#edf3f9] text-[#102a63] transition-colors duration-300 dark:bg-[#17131d] dark:text-white" dir="rtl">
  <header className="z-30 shrink-0 px-3 pt-3 sm:px-5"><div className="flex h-[64px] items-center gap-3 rounded-[20px] border border-[#d7e3ef] bg-[#f9fbfe] px-3 shadow-[0_10px_32px_rgba(44,72,104,.10)] transition-colors duration-300 dark:border-[#312b38] dark:bg-[#211c26] dark:shadow-[0_12px_38px_rgba(0,0,0,.28)]">
   <Link href="/Dashboard" className="flex items-center gap-2"><span className="relative grid h-10 w-10 place-items-center rounded-[13px] bg-gradient-to-br from-[#1681ff] to-[#0758e9] text-white"><Crown className="h-5 w-5 text-[#ffb019]"/><Wifi className="absolute bottom-1 h-2.5 w-2.5"/></span><span className="hidden leading-tight sm:block"><b className="block text-sm">LORD RADIUS</b><small className="text-[9px] font-bold tracking-wider text-[#e99100]">CUSTOMER SETUP</small></span></Link>
   <div className="mx-auto hidden items-center gap-2 lg:flex"><span className="setup-step setup-step-done"><Check className="h-3 w-3"/>الحساب</span><i className="h-px w-7 bg-[#cbd9e7] dark:bg-white/10"/><span className={`setup-step ${isPayment?"setup-step-done":isPlans?"setup-step-active":"setup-step-current"}`}><b>2</b>اختيار الخطة</span><i className="h-px w-7 bg-[#cbd9e7] dark:bg-white/10"/><span className={`setup-step ${isPayment?"setup-step-active":"opacity-55"}`}><b>3</b>الدفع والتفعيل</span></div>
   <div className="mr-auto flex items-center gap-2"><div className="hidden text-left sm:block"><div className="max-w-[180px] truncate text-xs font-bold">{account?.fullName||"Customer"}</div><div className="mt-0.5 text-[9px] text-slate-400">Customer</div></div><button onClick={()=>setTheme(mounted&&theme==="dark"?"light":"dark")} className="grid h-10 w-10 place-items-center rounded-full border border-[#d7e3ef] bg-white text-[#17386d] transition hover:-translate-y-0.5 hover:border-[#9fc4ec] dark:border-[#3b3442] dark:bg-[#17131d] dark:text-[#f4f6fb] dark:hover:border-[#4b6686]" aria-label="تغيير المظهر">{mounted&&theme==="dark"?<Sun className="h-4 w-4"/>:<Moon className="h-4 w-4"/>}</button><button onClick={logout} disabled={loggingOut} className="grid h-10 w-10 place-items-center rounded-full border border-red-200 bg-red-50 text-red-500 disabled:opacity-50 dark:border-red-500/25 dark:bg-red-500/10" aria-label="تسجيل الخروج"><LogOut className="h-4 w-4"/></button></div>
  </div></header>
  <main className="min-h-0 flex-1 p-3 sm:px-5 sm:pb-5"><div className="h-full min-h-0 overflow-y-auto overflow-x-hidden scroll-smooth rounded-[24px] border border-[#b9cee3] bg-[#f5f8fc] shadow-[0_18px_45px_rgba(39,69,103,.08)] dark:border-[#312b38] dark:bg-[#19151f] dark:shadow-[0_20px_50px_rgba(0,0,0,.22)]">{children}</div></main>
 <style jsx>{`.setup-step{display:inline-flex;height:32px;align-items:center;gap:7px;border:1px solid #d8e3ee;border-radius:999px;background:#f7faff;padding:0 12px;font-size:10px;font-weight:700;color:#728198}.setup-step b{display:grid;width:17px;height:17px;place-items:center;border-radius:50%;background:#e5edf6;color:#66768b;font-size:9px}.setup-step-done{border-color:#bfe3d5;background:#effaf5;color:#17845d}.setup-step-done :global(svg){color:#18a873}.setup-step-current,.setup-step-active{border-color:#b9d5fa;background:#edf5ff;color:#0758e9}.setup-step-current b,.setup-step-active b{background:#0758e9;color:white}:global(.dark) .setup-step{border-color:#3a3341;background:#19151f;color:#929aaa}:global(.dark) .setup-step b{background:#302a35;color:#b9c0cc}:global(.dark) .setup-step-done{border-color:rgba(33,180,122,.25);background:rgba(33,180,122,.08);color:#68d3aa}:global(.dark) .setup-step-current,:global(.dark) .setup-step-active{border-color:rgba(20,121,255,.32);background:rgba(20,121,255,.10);color:#83b6ff}:global(.dark) .setup-step-current b,:global(.dark) .setup-step-active b{background:#1479ff;color:#fff}`}</style>
 </div>
}