"use client";
import { Check, ChevronDown } from "lucide-react";
import { createPortal } from "react-dom";
import { useEffect, useRef, useState } from "react";
export type DropdownOption={value:string;label:string;hint?:string;dotClassName?:string};
export default function ProjectDropdown({value,onChange,options,placeholder="اختر...",className="",compact=false}:{value:string;onChange:(v:string)=>void;options:DropdownOption[];placeholder?:string;className?:string;compact?:boolean}){
 const [open,setOpen]=useState(false),[pos,setPos]=useState({top:0,left:0,width:180});const ref=useRef<HTMLDivElement>(null),buttonRef=useRef<HTMLButtonElement>(null),menuRef=useRef<HTMLDivElement>(null);const selected=options.find(o=>o.value===value);
 const place=()=>{const r=buttonRef.current?.getBoundingClientRect();if(!r)return;setPos({top:r.bottom+7,left:r.left,width:r.width})};
 useEffect(()=>{if(!open)return;place();const h=(e:MouseEvent)=>{const n=e.target as Node;if(!ref.current?.contains(n)&&!menuRef.current?.contains(n))setOpen(false)},p=()=>place();document.addEventListener("mousedown",h);window.addEventListener("resize",p);window.addEventListener("scroll",p,true);return()=>{document.removeEventListener("mousedown",h);window.removeEventListener("resize",p);window.removeEventListener("scroll",p,true)}},[open]);
 return <div ref={ref} className={`relative ${className}`} dir="rtl"><button ref={buttonRef} type="button" onClick={()=>{if(!open)place();setOpen(x=>!x)}} aria-expanded={open} className={`rl-action flex w-full items-center justify-between border bg-[#f9fbfe] px-3 font-semibold transition-all dark:bg-[#202f40] dark:text-slate-100 ${compact?"h-9 rounded-[11px] text-[11px]":"h-11 rounded-[14px] text-sm"} ${open?"border-[#6faaf0] ring-4 ring-[#1480ff]/10 dark:border-[#4f8fd8] dark:bg-[#21364d]":"border-[#d7e3ef] dark:border-white/10"}`}><span className="flex min-w-0 items-center gap-2 truncate">{selected?.dotClassName&&<span className={`h-2.5 w-2.5 shrink-0 rounded-full ${selected.dotClassName}`}/>}<span className="truncate">{selected?.label??placeholder}</span></span><ChevronDown className={`h-4 w-4 shrink-0 text-slate-400 transition-transform duration-300 ${open?"rotate-180":""}`}/></button>{open&&typeof document!=="undefined"&&createPortal(<div ref={menuRef} dir="rtl" className="ui-state-enter fixed z-[9999] rounded-[15px] border border-[#c7d8e8] bg-[#fbfdff] p-1.5 text-right shadow-[0_18px_45px_rgba(44,65,92,.24)] dark:border-white/[.14] dark:bg-[#223448] dark:shadow-[0_20px_48px_rgba(0,0,0,.38)]" style={{top:pos.top,left:pos.left,width:Math.max(pos.width,180)}}>{options.map(o=><button key={o.value} type="button" onClick={()=>{onChange(o.value);setOpen(false)}} className={`flex min-h-9 w-full items-center gap-2 rounded-[10px] px-3 text-right text-sm transition hover:bg-[#edf4fb] hover:text-[#0758e9] dark:hover:bg-white/[.07] ${o.value===value?"bg-[#edf4fb] text-[#0758e9] dark:bg-[#1479ff]/15 dark:text-[#8dbdff]":"text-slate-700 dark:text-slate-200"}`}>{o.dotClassName&&<span className={`h-2.5 w-2.5 shrink-0 rounded-full ${o.dotClassName}`}/>}<span className="min-w-0 flex-1"><span className="block truncate font-medium">{o.label}</span>{o.hint&&<span className="rl-note mt-0.5 block text-[13px] text-slate-400">{o.hint}</span>}</span>{o.value===value&&<Check className="h-4 w-4 shrink-0"/>}</button>)}</div>,document.body)}</div>
}